### PR TITLE
forum: improve deletion signature

### PR DESCRIPTION
**Pull request by iorveth**
Closes https://github.com/Joystream/joystream/issues/2482

### CODE REVIEW

**Review by shamil-gadelshin — CHANGES_REQUESTED** [review]
The linter is muted for this warning: `#![allow(clippy::type_complexity)]`

But the key (T::CategoryId, T::ThreadId, T::PostId) and the map `BTreeMap<(T::CategoryId, T::ThreadId, T::PostId), bool>` are very complex types. Can we introduce a struct instead of a tuple? Will it affect other systems? @Lezek123 @bedeho 

```
type ExtendedPostId<T> = ExtendedPostIdObject<T::CategoryId, T::ThreadId, T::PostId>


#[derive(Ord, .......)]
struct ExtendedPostIdObject<CategoryId, ThreadId, PostId>{
    category_id: CategoryId,
    thread_id: ThreadId, 
    post_id: PostId,
}
```

**Comment by Lezek123** [comment]
> The linter is muted for this warning: `#![allow(clippy::type_complexity)]`
> 
> But the key (T::CategoryId, T::ThreadId, T::PostId) and the map `BTreeMap<(T::CategoryId, T::ThreadId, T::PostId), bool>` are very complex types. Can we introduce a struct instead of a tuple? Will it affect other systems? @Lezek123 @bedeho
> 
> ```
> type ExtendedPostId<T> = ExtendedPostIdObject<T::CategoryId, T::ThreadId, T::PostId>
> 
> 
> #[derive(Ord, .......)]
> struct ExtendedPostIdObject<CategoryId, ThreadId, PostId>{
>     category_id: CategoryId,
>     thread_id: ThreadId, 
>     post_id: PostId,
> }
> ```

I think the idea of using `BTreeMap` here is to avoid duplicated ids and I'm not sure if a struct can be used as key in `BTreeMap`? When I tried this for the purpose of checking the `BTreeMap` encoding rules it was giving me some errors during the runtime build, while tuple/primitive keys weren't (It's very possible that I was doing something else wrong though, because of my lack of experience in runtime development)

**Comment by shamil-gadelshin** [comment]
> I think the idea of using `BTreeMap` here is to avoid duplicated ids, and I'm not sure if a struct can be used as key in `BTreeMap`? When I tried this for the purpose of checking the `BTreeMap` encoding rules it was giving me some errors during the runtime build, while tuple/primitive keys weren't (It's very possible that I was doing something else wrong though, because of my lack of experience in runtime development)

`BTreeMap` needs something that implements `Ord` trait (comparison) as a key. Most structs could get this implementation automatically in simple cases using `#[derive(Ord)]` attribute, and it will avoid duplicates. I don't see any possible problems from the runtime side (I could try to solve your mentioned issue with this if it is still actual). However, we might have a lot of other code that depends on the tuple (current implementation), and it would be impractical to change it now. Otherwise, the struct is a better choice, in my opinion.

**Comment by Lezek123** [comment]
> However, we might have a lot of other code that depends on the tuple (current implementation), and it would be impractical to change it now.

There will surely be a few changes needed in types, query-node mappings, integration tests etc., not sure what would be the impact on the runtime side.

**Comment by iorveth** [comment]
> > However, we might have a lot of other code that depends on the tuple (current implementation), and it would be impractical to change it now.
> 
> There will surely be a few changes needed in types, query-node mappings, integration tests etc., not sure what would be the impact on the runtime side.

It hope, it would be very local, unit tests & benchmarking adjustments mostly.

**Comment by shamil-gadelshin** [comment]
Please, try to implement it in the runtime. @iorveth

**Comment by iorveth** [comment]
> Please, try to implement it in the runtime. @iorveth

Done here https://github.com/Joystream/joystream/pull/2535/commits/5e0d4d0effd3b3f1756217c378d195569ddf276a

**Review by shamil-gadelshin — APPROVED** [review]
LGTM

**Pull request merged**
