### PR TITLE
Proposal codex upgrade

### PR DESCRIPTION
**Pull request by iorveth**
This PR aims to 
1. Refactor `proposals_codex` pallet according to https://github.com/Joystream/joystream/issues/1295
1. Fix check in ensure_entities_creation_limits_are_valid function.

### CODE REVIEW

**Review by shamil-gadelshin — APPROVED** [review]
LGTM

**Review by bedeho — CHANGES_REQUESTED** [review]
1. Haven't you forgot to update this so that the proposals actually work for the new working group? At least you would need to change enum `common::WorkingGroup`, no?

2. Also, some tests should have failed if I am correct, so there may be missing tests that actually attempt to submit proposals to this new working group

**Comment by iorveth** [comment]
Thanks for pointing an issue!

**Review by bedeho — CHANGES_REQUESTED** [review]
- Good fix on <= bug.
- Good fix on adding `Content` variant.
- You seem to have just replaced away all tests for Storage? dont we need tests to cover _all active groups_ ? So we need tests for both storage and content, and whenever a new group is added, we need tests for that also? Can't you just in each test case basically iterate over all variants and call some core test logic for each case? So for example something like

```Rust
#[test]
fn create_set_working_group_leader_reward_proposal_common_checks_succeed() {
    // This uses strum crate for enum iteration
    for group in WorkingGroup::iter() {
        run_create_set_working_group_leader_reward_proposal_common_checks_succeed(group);
    }
}

fn run_create_set_working_group_leader_reward_proposal_common_checks_succeed(group: WorkingGroup) {
initial_test_ext().execute_with(|| {
        let proposal_fixture = ProposalTestFixture {
            insufficient_rights_call: || {
                ProposalCodex::create_set_working_group_leader_reward_proposal(
                    RawOrigin::None.into(),
                    1,
                    b"title".to_vec(),
                    b"body".to_vec(),
                    None,
                    0,
                    10,
                    group,
                )
            },
            empty_stake_call: || {
                ProposalCodex::create_set_working_group_leader_reward_proposal(
                    RawOrigin::Signed(1).into(),
                    1,
                    b"title".to_vec(),
                    b"body".to_vec(),
                    None,
                    0,
                    10,
                    group,
                )
            },
            invalid_stake_call: || {
                ProposalCodex::create_set_working_group_leader_reward_proposal(
                    RawOrigin::Signed(1).into(),
                    1,
                    b"title".to_vec(),
                    b"body".to_vec(),
                    Some(<BalanceOf<Test>>::from(5000u32)),
                    0,
                    10,
                    group,
                )
            },
            successful_call: || {
                ProposalCodex::create_set_working_group_leader_reward_proposal(
                    RawOrigin::Signed(1).into(),
                    1,
                    b"title".to_vec(),
                    b"body".to_vec(),
                    Some(<BalanceOf<Test>>::from(50000u32)),
                    10,
                    10,
                    group,
                )
            },
            proposal_parameters:
                crate::proposal_types::parameters::set_working_group_leader_reward_proposal::<Test>(
                ),
            proposal_details: ProposalDetails::SetWorkingGroupLeaderReward(
                10,
                10,
                    group,
            ),
        };
        proposal_fixture.check_all();
    });
}
```

**Review by bedeho — APPROVED** [review]
Nice work.

**Pull request merged**
