### PR TITLE
Spelling, Grammar and Formatting

### PR DESCRIPTION
**Pull request by blrhc**
A more in-depth review of the README file in this repository.

### CODE REVIEW

**Comment by bwhm** [comment]
Thanks, but I'm going to put this on hold until after we merge #75 some time this week...

I hope you don't mind...

**Comment by blrhc** [comment]
Ah, ok! 
Shall I refrain from making any more README PRs? 
Or is it just that there will be a slight delay in merging them in this specific repository?

**Comment by bwhm** [comment]
> Ah, ok @bwhm!
> Shall I refrain from making any more README PRs?
> Or is it just that there will be a slight delay in merging them in this specific repository?

Ideally, announce in the bounty issue that you are working on it. That way, there are no misunderstandings. When you start, perhaps open a draft PR, so you can fix all in one go instead of 10 separate fixes...

If there are open PRs that appears to be active, it's best to wait (like with this one).

**Comment by blrhc** [comment]
Understood, thanks for the clarification.

**Comment by bwhm** [comment]
Hey @blrhc 
Sorry for the delay. We are going to kill the close the existing Rome PR #75 , and open a new one.

If you are able to pull in the changes since you opened this today, it would perhaps be easier for all of us! All add an extra $10 for your troubles...

**Comment by blrhc** [comment]
Ok that sounds good, when you say changes since I opened this, do you mean correcting any further errors that might have appeared since I first sent the PR?

**Comment by bwhm** [comment]
That would be up to you to decide.

Just pull in the latest changes, make any additional changes if you want, and ping me when it's ready for review :)

**Comment by blrhc** [comment]
Ready for review.

**Pull request merged**
