### PR TITLE
"Abstain" votes shouldn't count as "No"

### PR DESCRIPTION
**Pull request by singulart**
In the current implementation, "Abstain" votes are treated as votes against the proposal. This simple improvement is about not taking such votes into account when calculating thresholds. I've also added some more unit tests. 

See https://mrsc.org/Home/Stay-Informed/MRSC-Insight/April-2013/How-Are-Abstentions-Handled-When-Counting-Votes.aspx

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201703380142370/1201703462643764) by [Unito](https://www.unito.io)

### CODE REVIEW

**Comment by bwhm** [comment]
I think this is the right idea, but I'm not sure if this fix would be obsoleted by the many changes in `olympia`. @bedeho?

**Comment by bedeho** [comment]
This is being addressed here https://github.com/Joystream/joystream/issues/2953

**Review by shamil-gadelshin — COMMENTED** [review]
We opted for another algorithm: https://github.com/Joystream/joystream/issues/2953

This PR helped to advance the discussion. Thank you.

**Comment by mnaamani** [comment]
Looks like this PR can be closed?

**Pull request closed without merging**
