### PR TITLE
query-node: adding remaining working groups to bootstrap

### PR DESCRIPTION
**Pull request by mnaamani**
We incorrectly assumed some working groups will loose their state and so we did not include them in the bootstrapping process. I added remaining groups in this PR.

### CODE REVIEW

**Comment by mnaamani** [comment]
aah I get error when using it against chain that is already upgraded (even when I set block before runtime upgrade). looks like I need to bring back your trick of loading metadata for prior runtime?

```
TypeError: Cannot read property 'workerById' of undefined
    at getWorkingGroupData (/root/joystream/query-node/mappings/bootstrap-data/scripts/fetchWorkingGroupsData.ts:48:50)
    at main (/root/joystream/query-node/mappings/bootstrap-data/scripts/fetchWorkingGroupsData.ts:26:20)
```

**Comment by mnaamani** [comment]
In 03ee58185f0157f8b44b37cc33a512615f88ab75 I added sumer types, but of course the problem is now that the types of the new chain are not defined. So I will have to use a hybrid custom defs.json file.

```
2021-11-11 14:53:50        REGISTRY: Unable to resolve type StorageBucketsPerBagValueConstraint, it will fail on construction
2021-11-11 14:53:50        API/INIT: Error: FATAL: Unable to initialize the API: createType(StorageBucketsPerBagValueConstraint):: DoNotConstruct: Cannot construct unknown type StorageBucketsPerBagValueConstraint
    at EventEmitter.value (/root/joystream/node_modules/@polkadot/api/base/Init.cjs:82:25)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

**Comment by Lezek123** [comment]
We didn't have mappings for those working groups before. We only had ones for `Storage` and `Gateway` working groups (the `Storage` ones were the only ones actually used by Atals, because it needed the storage worker metadata).

If we're introducing mappings for new groups we'll need changes in a few more places:
- `query-node/manifest.yml` (update `eventHandlers`)
- `query-node/mappings/workingGroup.ts` (update `getWorkerType`)

**Comment by Lezek123** [comment]
> In [03ee581](https://github.com/Joystream/joystream/commit/03ee58185f0157f8b44b37cc33a512615f88ab75) I added sumer types, but of course the problem is now that the types of the new chain are not defined. So I will have to use a hybrid custom defs.json file.
> 
> ```
> 2021-11-11 14:53:50        REGISTRY: Unable to resolve type StorageBucketsPerBagValueConstraint, it will fail on construction
> 2021-11-11 14:53:50        API/INIT: Error: FATAL: Unable to initialize the API: createType(StorageBucketsPerBagValueConstraint):: DoNotConstruct: Cannot construct unknown type StorageBucketsPerBagValueConstraint
>     at EventEmitter.value (/root/joystream/node_modules/@polkadot/api/base/Init.cjs:82:25)
>     at processTicksAndRejections (internal/process/task_queues.js:95:5)
> ```

You can use custom chain metadata (ie. Sumer metadata) when initializing the api, which should solve this issue.

**Edit:** I found a nice clean solution for that in the version of the api, by using `await api.at(BLOCK_HASH)`: https://github.com/polkadot-js/api/issues/3871

**Comment by mnaamani** [comment]
> We didn't have mappings for those working groups before. We only had ones for `Storage` and `Gateway` working groups (the `Storage` ones were the only ones actually used by Atals, because it needed the storage worker metadata).
> 
> If we're introducing mappings for new groups we'll need changes in a few more places:
> 
>     * `query-node/manifest.yml` (update `eventHandlers`)
> 
>     * `query-node/mappings/workingGroup.ts` (update `getWorkerType`)

Good point. I had updated `getWorkerType()` but forgot about `eventHandlers` section in manifest. :+1: 

I think for Giza we will just need the Storage (for uploads) and Distributor groups (for playback). We will not need Gateway working group support.

**Comment by mnaamani** [comment]
> > In [03ee581](https://github.com/Joystream/joystream/commit/03ee58185f0157f8b44b37cc33a512615f88ab75) I added sumer types, but of course the problem is now that the types of the new chain are not defined. So I will have to use a hybrid custom defs.json file.
> > ```
> > 2021-11-11 14:53:50        REGISTRY: Unable to resolve type StorageBucketsPerBagValueConstraint, it will fail on construction
> > 2021-11-11 14:53:50        API/INIT: Error: FATAL: Unable to initialize the API: createType(StorageBucketsPerBagValueConstraint):: DoNotConstruct: Cannot construct unknown type StorageBucketsPerBagValueConstraint
> >     at EventEmitter.value (/root/joystream/node_modules/@polkadot/api/base/Init.cjs:82:25)
> >     at processTicksAndRejections (internal/process/task_queues.js:95:5)
> > ```
> 
> You can use custom chain metadata (ie. Sumer metadata) when initializing the api, which should solve this issue.
> 
> **Edit:** I found a nice clean solution for that in the version of the api, by using `await api.at(BLOCK_HASH)`: [polkadot-js/api#3871](https://github.com/polkadot-js/api/issues/3871)

Nice find. I'll look into that.

**Pull request closed without merging**
