### PR TITLE
Query node/use published legacy index builder lib

### PR DESCRIPTION
**Pull request by mnaamani**
- Update to use `hydra-indexer-lib@0.0.18-legacy.1.26.1` with Polkadot api ver 1.26.1
- Updated to use warthog https://github.com/metmirr/warthog/releases/tag/2.9.7
- Fixed issue with passing `WS_PROVIDER_ENDPOINT_URI` env variable to docker-compose

### CODE REVIEW

**Comment by mnaamani** [comment]
The update for warthog was done because @bwhm reported below error on yarn install:

```
error https://github.com/metmirr/warthog/releases/download/v2.19/warthog-v2.19.tgz: Integrity check failed for "warthog" (computed integrity doesn't match our records, got "sha512-ls8Axo/1ywUg8GXhE45SxUCzxm3FK24rRgJj/ZggDXKca0HDyvVRGcZFFNPZ6s1DEWIaYp9UEy6qGsY9dySMUQ== sha1-wHJGVTstD8n7CHvcwXmU4GBRosQ=")
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
warning url-loader@1.1.2: Invalid bin field for "url-loader".
```

Which I was able to confirm when yarn cache is cleared or building on fresh machine. I suppose that was due to archiving the older version? Does the latest version of hydra-cli update the dependencies for `graphql-server` generated pacakge accordingly?

**Comment by dzhelezov** [comment]
> The update for warthog was done because @bwhm reported below error on yarn install:
> 
> ```
> error https://github.com/metmirr/warthog/releases/download/v2.19/warthog-v2.19.tgz: Integrity check failed for "warthog" (computed integrity doesn't match our records, got "sha512-ls8Axo/1ywUg8GXhE45SxUCzxm3FK24rRgJj/ZggDXKca0HDyvVRGcZFFNPZ6s1DEWIaYp9UEy6qGsY9dySMUQ== sha1-wHJGVTstD8n7CHvcwXmU4GBRosQ=")
> info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
> warning url-loader@1.1.2: Invalid bin field for "url-loader".
> ```
> 
> Which I was able to confirm when yarn cache is cleared or building on fresh machine. I suppose that was due to archiving the older version? Does the latest version of hydra-cli update the dependencies for `graphql-server` generated pacakge accordingly?

Thanks for reporting.  That’s indeed due to a hard coded warthog version in hydra-cli, which should’ve been updated. Will look into it

**Comment by metmirr** [comment]
Mokthar warthog version `2.19` is the latest version and we should use that (sorry for version confusion)

**Comment by mnaamani** [comment]
> Mokthar warthog version `2.19` is the latest version and we should use that (sorry for version confusion)

Thanks for clarification, I based it on the date sorry. So how do we solve the issue. yarn seems to be failing to fetch it, I'm wondering if it is because of the redirect:

```
MokoBook:tmp mokhtar$ wget https://github.com/metmirr/warthog/archive/v2.19.tar.gz
--2020-11-02 13:50:50--  https://github.com/metmirr/warthog/archive/v2.19.tar.gz
Resolving github.com (github.com)... 13.234.176.102
Connecting to github.com (github.com)|13.234.176.102|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://codeload.github.com/metmirr/warthog/tar.gz/v2.19 [following]
--2020-11-02 13:50:50--  https://codeload.github.com/metmirr/warthog/tar.gz/v2.19
Resolving codeload.github.com (codeload.github.com)... 13.127.152.42
Connecting to codeload.github.com (codeload.github.com)|13.127.152.42|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/x-gzip]
Saving to: ‘v2.19.tar.gz’

v2.19.tar.gz                         [      <=>                                                ] 972.70K   726KB/s    in 1.3s    

2020-11-02 13:50:52 (726 KB/s) - ‘v2.19.tar.gz’ saved [996042]
```

**Comment by mnaamani** [comment]
After discussion we will update to https://github.com/metmirr/warthog/releases/tag/v2.20.0

**Review by metmirr — APPROVED** [review]
LGTM!

**Pull request merged**
