### PR TITLE
Pioneer: Exploring old proposals

### PR DESCRIPTION
**Pull request by Lezek123**
Implements https://github.com/Joystream/joystream/issues/1354

In order to re-create `historical-proposals.json` file:
1. Checkout https://github.com/Lezek123/substrate-runtime-joystream/tree/proposals-export-script locally
2. `yarn && yarn workspace pioneer start`
3. Go to http://localhost:3000/#/js (connect to the current testnet node)
4. Select `Export proposals data`
5. Run the script

### CODE REVIEW

**Review by bwhm — APPROVED** [review]
Looks great to me!

*this link won't work for long, but:
https://alexandria-testing-4.joystream.app/#/proposals/historical

**Comment by mnaamani** [comment]
Solution looks great.
I am having trouble running the export script though.

In browser console:
```
Uncaught (in promise) TypeError: _transport.default is not a constructor
    _runJs http://localhost:3000/main.00476fde.js:184626
    apply http://localhost:3000/vendor.4e747629.js:20094
    baseInvoke http://localhost:3000/vendor.4e747629.js:21755
    apply
```

Getting some build errors in pioneer:
```
Version 3.7.2
app-js/src/Playground.tsx:30:8 - error TS2613: Module '"/Users/mokhtar/joystream/joystream/pioneer/packages/joy-utils/src/Transport"' has no default export. Did you mean to use 'import { Transport } from "/Users/mokhtar/joystream/joystream/pioneer/packages/joy-utils/src/Transport"' instead?

30 import Transport from '@polkadot/joy-utils/transport';
          ~~~~~~~~~
```

I will try to remove all my node_modules/ folders and try to rebuild. Its probably something local because I see all the CI checks have passed.

edit:

Hmm I think this may be another case of import resolution due to case sensitive issue with the name of the file `joy-utils/src/Transport.tsx` vs `joy-utils/src/transport/` folder.  @Lezek123

**Comment by mnaamani** [comment]
> Looks great to me!
> 
> *this link won't work for long, but:
> https://alexandria-testing-4.joystream.app/#/proposals/historical

Tested it there.. looks great, almost wish the live view was as snippy. 👍 

Although the Query node will help, it might not hurt to use a similar mechanism to display the live content.
Just have the "status-server" do regular exports and serve a live.json which pioneer can fetch.

**Comment by mnaamani** [comment]
Only thing that breaks and maybe be worth fixing, are links to old proposals in a proposal text like `https://testnet.joystream.org/#/proposals/83` which is referenced from the historical proposal: https://alexandria-testing-4.joystream.app/#/proposals/historical/88

Some regex match and replace magic perhaps?

**Comment by mnaamani** [comment]
> Hmm I think this may be another case of import resolution due to case sensitive issue with the name of the file `joy-utils/src/Transport.tsx` vs `joy-utils/src/transport/` folder. @Lezek123

The build issue is on my Mac

**Comment by mnaamani** [comment]
I fixed it by just adding extra `/index` at the end to be more explicit

`import Transport from '@polkadot/joy-utils/transport/index';`

**Comment by mnaamani** [comment]
One suggestion is to perhaps use the `FileSaver` api to download the exported state instead of pasting it to console.

const data = JSON.stringify(allProposalsData, null, 4)
const blob = new Blob([data], { type: 'application/json; charset=utf-8' });
FileSaver.saveAs(blob, `historical-proposals.json`);

I think we do something like this when users apply for a role and we generate a new key for them.

**Review by mnaamani — APPROVED** [review]

**Comment by Lezek123** [comment]
`@polkadot/joy-utils/src/Transport.tsx` is no longer part of the repository on `iznik` branch, but I had to place the export script on a branch based on `master`, because of the dependencies like `@polkadot/api`, `@polkadot/types` etc. (and there this file is still present). I didn't notcie this, but actually the Mac OS check indeed caught it: https://github.com/Lezek123/substrate-runtime-joystream/runs/1123661907. Will fix.

> Although the Query node will help, it might not hurt to use a similar mechanism to display the live content.

Maybe we could leverage this somehow, but this would require factoring the `joy-utils` out into `joystream-js` first (then it could be "consumed" by the status server). I'm planning to do this as soon as possible, because this will have a lot of potential benefits.

>Only thing that breaks and maybe be worth fixing, are links to old proposals (...) Some regex match and replace magic perhaps?

Will do

> One suggestion is to perhaps use the `FileSaver` api to download the exported state instead of pasting it to console.

Good idea, will implement.

**Comment by mnaamani** [comment]
Nice https://github.com/Joystream/joystream/pull/1381/commits/3c978576ccd19f5789c961440f602d3ac19fb905
Just wondering if there could also be links in the proposal discussion posts?

**Comment by Lezek123** [comment]
> Just wondering if there could also be links in the proposal discussion posts?

Done (but couldn't find any examples)

**Comment by Lezek123** [comment]
> One suggestion is to perhaps use the FileSaver api to download the exported state instead of pasting it to console.

Implemented on https://github.com/Lezek123/substrate-runtime-joystream/tree/proposals-export-script

**Comment by mnaamani** [comment]
> Implemented on https://github.com/Lezek123/substrate-runtime-joystream/tree/proposals-export-script


Screen Shot 2020-09-17 at 12 53 19 PM

Exporting Works.

And Proposals links updated:
Screen Shot 2020-09-17 at 1 01 18 PM

**Pull request merged**
