### PR TITLE
Update class permissions extrinsic fix

### PR DESCRIPTION
**Pull request by iorveth**
The PR consists of: 

1. `ClassById` and `EntityById` related runtime storage entities reworking to make them configurable through `chain_spec` config. 

1. Update class permissions extrinsic fix.

Closes: https://github.com/Joystream/joystream/issues/1357
Fix for https://github.com/Joystream/joystream/issues/1540

### CODE REVIEW

**Comment by mnaamani** [comment]
The fix looks good. Perhaps in the test coverage also include case for when maintainer group is removed from a class permissions and verify decremented number of maintained classes for that group.

There are clippy errors for the versioned store..
```
error: match expression looks like `matches!` macro

   --> runtime-modules/versioned-store/src/lib.rs:711:9

    |

711 | /         match (value, prop.prop_type) {

712 | |             (PV::None,        PT::None) |

713 | |

714 | |             // Single values

...   |

738 | |             _ => false,

739 | |         }

    | |_________^

    |

    = note: `-D clippy::match-like-matches-macro` implied by `-D warnings`

    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#match_like_matches_macro

help: try this

    |

711 |         matches!((value, prop.prop_type), (PV::None,        PT::None) |

712 | 

713 |             // Single values

714 |             (PV::Bool(_),     PT::Bool) |

715 |             (PV::Uint16(_),   PT::Uint16) |

716 |             (PV::Uint32(_),   PT::Uint32) |

  ...

error: aborting due to previous error

error: could not compile `pallet-versioned-store`.

To learn more, run the command again with --verbose.

warning: build failed, waiting for other jobs to finish...

error: build failed

The command "BUILD_DUMMY_WASM_BINARY=1 cargo clippy --release --all -- -D warnings" exited with 101.
```

Why don't we just get rid of it?

**Comment by iorveth** [comment]
@mnaamani just upgraded test coverage to reflect this case here. https://github.com/Joystream/joystream/pull/1542/commits/5ea0dc13de991e4bec77195be259747ca2ae50ff

**Comment by iorveth** [comment]
Why don't we just get rid of it?



> The fix looks good. Perhaps in the test coverage also include case for when maintainer group is removed from a class permissions and verify decremented number of maintained classes for that group.
> 
> There are clippy errors for the versioned store..
> 
> ```
> error: match expression looks like `matches!` macro
> 
>    --> runtime-modules/versioned-store/src/lib.rs:711:9
> 
>     |
> 
> 711 | /         match (value, prop.prop_type) {
> 
> 712 | |             (PV::None,        PT::None) |
> 
> 713 | |
> 
> 714 | |             // Single values
> 
> ...   |
> 
> 738 | |             _ => false,
> 
> 739 | |         }
> 
>     | |_________^
> 
>     |
> 
>     = note: `-D clippy::match-like-matches-macro` implied by `-D warnings`
> 
>     = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#match_like_matches_macro
> 
> help: try this
> 
>     |
> 
> 711 |         matches!((value, prop.prop_type), (PV::None,        PT::None) |
> 
> 712 | 
> 
> 713 |             // Single values
> 
> 714 |             (PV::Bool(_),     PT::Bool) |
> 
> 715 |             (PV::Uint16(_),   PT::Uint16) |
> 
> 716 |             (PV::Uint32(_),   PT::Uint32) |
> 
>   ...
> 
> error: aborting due to previous error
> 
> error: could not compile `pallet-versioned-store`.
> 
> To learn more, run the command again with --verbose.
> 
> warning: build failed, waiting for other jobs to finish...
> 
> error: build failed
> 
> The command "BUILD_DUMMY_WASM_BINARY=1 cargo clippy --release --all -- -D warnings" exited with 101.
> ```
> 
> Why don't we just get rid of it?

I don`t sure if we can drop this module now, seems that @bedeho was concerned about some issues, that can show up if we do so.

**Comment by mnaamani** [comment]
> I don`t sure if we can drop this module now, seems that @bedeho was concerned about some issues, that can show up if we do so.

Fair enough, it seems anyway that the builder is passing now correctly anyway in the docker image build step.

**Review by mnaamani — APPROVED** [review]
LGTM

Again the 'Content Directory Initializing' CI job fails because we need to update the joystream/types to reflect the reafctoring:

```
$ ts-node ./scripts/initializeContentDir.ts
Initializing the api (ws://127.0.0.1:9944)...
Unknown types found, no types for ClassOf, EntityOf
Initializing classes (13 input files found)...

Initializing schemas (13 input files found)...

Unable to resolve type ClassOf, it will fail on construction
Unable to decode storage unknown.unknown: createType(ClassOf):: Cannot construct unknown type ClassOf
2020-10-17 14:33:12        RPC-CORE: queryStorageAt(keys: Vec<StorageKey>, at?: BlockHash): Vec<StorageChangeSet>:: createType(ClassOf):: Cannot construct unknown type ClassOf
2020-10-17 14:33:12             DRR: Error: createType(ClassOf):: Cannot construct unknown type ClassOf
```

**Comment by mnaamani** [comment]
@iorveth  could you merge updated babylon branch again, @Lezek123 added joystream/types fixes in #1556 so the checks should run again succesfully now.

**Comment by iorveth** [comment]
Done

**Comment by mnaamani** [comment]
The storage-node CI checks is failing in this job run. I suspect it is due ipns name publishing not completing in allotted time for the test. Will fix in another PR.
The important thing is the runtime intergartion test and content direct init tests are now passing.

**Pull request merged**
