### PR TITLE
Ephesus: post-merge fixes

### PR DESCRIPTION
**Pull request by Lezek123**
- In `run-network-tests.yml`: `actions/checkout@v3` and `actions/setup-node@v3` were (probably accidently) downgraded to `v1` during the merge, updated to `v3`.
- `project-token/src/lib.rs`: Fixed duplicated `TransferDestinationMemberDoesNotExist` check
- Removed no longer useful `SUDO_ACCOUNT_URI` env variable from integration tests
- `network-tests/src/consts.ts`: Removed `getWorkingGroupNameByModuleName` as it was pretty much a duplicate of `workingGroupNameByModuleName` const
- Network tests: Refactored flows that need to top up WG budget to use `fundWorkingGroupBudget` tx instead of proposal for simplicity
- Added missing `WorkingGroupBudgetFunded` event mapping (https://github.com/Joystream/joystream/issues/4625)
- `network-tests/src/cli/joystream.ts` - removed redundant `exitCode` checks for commands executed without `expectSuccess=false` flag. They were redundant, because in this case any `exitCode` other than `0` will just throw an error.
- Fixed resource locking in `network-tests/src/flows/proposals/index.ts`
- Removed a few unused fixtures that relied on sudo: `CreateLeadOpeningFixture`, `SetBudgetFixture`, `SetLeaderInvitationQuotaFixture`, `CreateMemberHappyCaseFixture`
- Removed unused flows that relied on sudo: `creatingFoundingMembers`, `creatingMembers`
- Removed a few other references to `sudo` and some unused code

### CODE REVIEW

**Review by dobertRowneySr — APPROVED** [review]
LGTM

**Comment by mnaamani** [comment]
> * Added missing `WorkingGroupBudgetFunded` event mapping (

Do we need this on master as well?

**Comment by Lezek123** [comment]
> Do we need this on master as well?

Oh, sure, I was planning to prepare a PR for master as well, I'll create one in a sec.

**Review by mnaamani — APPROVED** [review]
Nice cleanup, there are other scripts in `utils/api-scripts` with dependency on sudo which we can probably drop. Even the migration scripts for that matter. But not critical now.

**Pull request merged**
