### PR TITLE
Query node indexer start options

### PR DESCRIPTION
**Pull request by metmirr**
This PR adds the option to start indexer from a block number. Block number is passed as an argument:

```
yarn start --height 123
```

If block number is not provided either block number is `0` or retrieved from the database.

_Note_: `Bootstrapper.ts` file update is mostly white space removal so can be ignored.

### CODE REVIEW

**Review by dzhelezov — APPROVED** [review]

**Comment by dzhelezov** [comment]
> If block number is not provided either block number is 0 or retrieved from the database.

What happens if the provided height is greater than the one in the database?

**Comment by metmirr** [comment]
If block height is provided then the block height in the database is ignored. I thought it as a forcing option.

**Comment by dzhelezov** [comment]
> If block height is provided then the block height in the database is ignored. I thought it as a forcing option.

Isn't it a dangerous situation? Assume the indexer was stopped at block 200, and then started at block height 100. The events from block 100 and further on will be applied to the current state in the database (which is at block 200 and out sync). Probably one should just throw an error and allow a custom block height only if there's no previous history in the database.

**Comment by metmirr** [comment]
> > If block height is provided then the block height in the database is ignored. I thought it as a forcing option.
> 
> Isn't it a dangerous situation? Assume the indexer was stopped at block 200, and then started at block height 100. The events from block 100 and further on will be applied to the current state in the database (which is at block 200 and out sync). Probably one should just throw an error and allow a custom block height only if there's no previous history in the database.

You are right, it is dangerous. Thanks, will do a fix!

**Review by bedeho — APPROVED** [review]
LGTM.

**Pull request merged**
