### PR TITLE
Joystream cli

### PR DESCRIPTION
**Pull request by metmirr**

### CODE REVIEW

**Comment by mnaamani** [comment]
So the problem with using input argument is that it is requiring the media location, but is not known until after the upload is done.

```
    media: {
        new: {
            encoding: 71,
            pixelWidth: 1280,
            pixelHeight: 720,
            size: 736084,
            location: {
                new: {
                    joystreamMediaLocation: {
                        new: {
                            dataObjectId: "5DEwbahjZe7ZB2BwmwMzCdR1AJzu5ZkcfMLH5YPB7HC3DPFf"
                        }
                    }
                }
            }
        }
    },
```

So in the input it only really makes sense to include some values and the location would be filled by the command.

```
"media": {
      "new": {
          "encoding": 71,
          "pixelWidth": 1280,
          "pixelHeight": 720,
          "size": 736084
      }
    }
```


This is the input file I tried to use:
```
{
    "title": "my video",
    "description": "my video",
    "thumbnailURL": "",
    "duration": 5,
    "isPublic": true,
    "isExplicit": true,
    "hasMarketing": true,
    "skippableIntroDuration": 0,
    "channel": 93,
    "language": 23,
    "category": 2,
    "license": {
        "new": {
            "knownLicense": 17
        }
    },
    "publishedBeforeJoystream": null,
    "media": {
      "new": {
          "encoding": 71,
          "pixelWidth": 1280,
          "pixelHeight": 720,
          "size": 736084
      }
    }
}
```

using command:
`yarn joystream-cli media:uploadVide ~/Downloads/video.mp4 -c 93 -i input.json`

**Comment by mnaamani** [comment]
I suppose the channel field in the input file can also be optional if specified on the command line with the `-c` argument

**Comment by Lezek123** [comment]
Created a PR with suggested changes: https://github.com/metmirr/joystream/pull/3

The input I used:
```
{
    "title": "my video",
    "description": "my video",
    "thumbnailURL": "",
    "isPublic": true,
    "isExplicit": true,
    "hasMarketing": true,
    "language": { "existing": { "code": "EN" } },
    "category": { "existing": { "name": "Music" } },
    "license": { "new": { "knownLicense": { "existing": { "code": "CC_BY" } } } },
    "media": {
      "new": {
        "encoding": { "existing": { "name": "H.264_MP4" } }
      }
    }
}
```

**Review by Lezek123 — CHANGES_REQUESTED** [review]
Created a PR with suggested changes: https://github.com/metmirr/joystream/pull/3

Succesfully tested with this input:
```
{
    "title": "my video",
    "description": "my video",
    "thumbnailURL": "",
    "isPublic": true,
    "isExplicit": true,
    "hasMarketing": true,
    "language": { "existing": { "code": "EN" } },
    "category": { "existing": { "name": "Music" } },
    "license": { "new": { "knownLicense": { "existing": { "code": "CC_BY" } } } },
    "media": {
      "new": {
        "encoding": { "existing": { "name": "H.264_MP4" } }
      }
    }
}
```

**Comment by mnaamani** [comment]
Thanks for collaboration on this @Lezek123 LGTM

**Comment by mnaamani** [comment]
I think this PR needs updating after the field name changes..

```
 Error: src/commands/media/uploadVideo.ts(259,7): error TS2322: Type '"thumbnailURL"' is not assignable to type '"title" | "description" | "license" | "isPublic" | "language" | "isCensored" | "channel" | "category" | "duration" | "skippableIntroDuration" | "thumbnailUrl" | "media" | "hasMarketing" | "publishedBeforeJoystream" | "isExplicit"'.
```

**Pull request merged**
