### PR TITLE
Drop MultiAddress

### PR DESCRIPTION
**Pull request by mnaamani**
We do not actually need [MultiAddress](https://paritytech.github.io/substrate/master/sp_runtime/enum.MultiAddress.html) as our Address type.

Or do we need it to support Multisig ?

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202132419573087/1202545045238027) by [Unito](https://www.unito.io)

### CODE REVIEW

**Review by Lezek123 — COMMENTED** [review]
Looks good, but there are conflicts to resolve.

> Or do we need it to support Multisig ?

I don't think so, but we seem to need `asMulti` and `approveAsMulti` as part of `api.tx.utility` / `api.tx.multisig`, so I can't really test it right now.

**Comment by mnaamani** [comment]
Fixed conflicts.
Regarding multi-sig, I'll look into it.

**Comment by mnaamani** [comment]
Fixed conflicts.. again ;)
Looked into multisig pallet. the `other_signatories` is always a `Vec<T::AccountId>` so there is no dependence on the `Address` type in the runtime being a `MultiAddress`, so we can safely drop it.

**Review by Lezek123 — APPROVED** [review]
LGTM

**Pull request merged**
