### PR TITLE
My roles - add Worker ID

### PR DESCRIPTION
**Pull request by Lezek123**
SSIA

### CODE REVIEW

**Comment by mnaamani** [comment]
Is it normal not to see my role as content workinging group lead if I set it via sudo rather than going through hiring process?

**Comment by mnaamani** [comment]
> Is it normal not to see my role as content workinging group lead if I set it via sudo rather than going through hiring process?

Same member id is also storage load, assigned through hiring process, and that showed up in my roles correctly

**Comment by Lezek123** [comment]
> Is it normal not to see my role as content workinging group lead if I set it via sudo rather than going through hiring process?
> Same member id is also storage load, assigned through hiring process, and that showed up in my roles correctly

Storage Working Group lead is quite different, because technically he's part of the "workers" group, so it's easy to include this role in `my-roles`. Including Content Working Group lead role would require some addiotional handling, since it's kind of "separated", doesn't have `workerId` etc.

It can be done, but not sure if it's necessary.

**Comment by mnaamani** [comment]
okay thanks for the clarification.

I think right now its not necessary.

**Comment by mnaamani** [comment]
LGTM will merge unless @bwhm has any additional issue re showing content working group lead role info

Screen Shot 2020-07-16 at 6 39 31 PM

**Review by mnaamani — APPROVED** [review]

**Pull request merged**
