### PR TITLE
CLI: Minor improvements

### PR DESCRIPTION
**Pull request by Lezek123**
This PR contains two minor improvements for the CLI:
- Based on @bwhm's input I overriden the names of some of the struct fields of the `commitment` extrinsic parameter in the UI (ie. `terminate_curator_application_stake_unstaking_period`) in order for them not to contain the word `curator`. This is actually caused by the flat namespace issue w.r.t. `OpeningPolicy`, which is defined both in `working-groups` and `content-working-group` module in the runtime (the issue is described in a comment above `WorkingGroupOpeningPolicyCommitment` in `joystream/joystream/types/src/working-group/index.ts`), but could be quite easily solved in the CLI thanks to the "parameters decorating/overriding" mechanism I implemented earlier.
- Added unstaking periods listing in the output of `working-groups:opening` command, so that it's now easier to check whether the opening we created has correct unstaking periods (I wasn't sure if it's necessary before, but now that we established that at least 2 of those periods will be quite important I just decided to list all of them)

### CODE REVIEW

**Comment by Lezek123** [comment]
Added more impovements based on issue https://github.com/Joystream/joystream/issues/1029:
- Prompts for setting api URI for the first time when not yet set
- Improved missing account flow (+ added `account:import` suggestion)
- Removed potentially confusing `Opening ID` from openings list (`working-groups:openings`)

In order to test the new behavior it's best to remove `accounts` folder and `state.json` file from the `joystream-cli` data directory, which is:
- `/home/<Username>/.local/share/joystream-cli` (Linux)
- `c:\Users\<Username>\AppData\Roaming\joystream-cli` (Windows)
- `/Users/<Username>/Library/Application Support/joystream-cli` (Mac OS)

**Comment by Lezek123** [comment]
More improvements:
- Not showing `0x` as default value (to avoid confusion)
- `working-groups:overview` - now highlighting workers for which role keys are available in the CLI (excluding `Alice` and `Bob`)
- Current group (name) is now logged in the console when executing `working-groups`-family commands

**Review by bwhm — APPROVED** [review]
Only reviewing functionality, not the code itself:

> Based on @bwhm's input I overriden the names of some of the struct fields of the commitment extrinsic parameter in the UI (ie. terminate_curator_application_stake_unstaking_period) in order for them not to contain the word curator. This is actually caused by the flat namespace issue w.r.t. OpeningPolicy, which is defined both in working-groups and content-working-group module in the runtime (the issue is described in a comment above WorkingGroupOpeningPolicyCommitment in joystream/joystream/types/src/working-group/index.ts), but could be quite easily solved in the CLI thanks to the "parameters decorating/overriding" mechanism I implemented earlier.

Looks great!
Although it's still quite a chore to fill out the `createOpening`, my only real issue is this:
```
  Providing values for human_readable_text struct:
    Provide value for version (0) 
```
Perhaps we should either default to 1 here (I think this is the version still?), or just don't ask and set it to 1?

Not urgent or important, but:
1. It's a nice feature that you can save your `createdOpening`s as drafts, but it's not clear how I can use/edit the draft for later openings?
2. Perhaps you can display the `Human readable text` to confirm before you submit the extrinsic?

> Added unstaking periods listing in the output of working-groups:opening command, so that it's now easier to check whether the opening we created has correct unstaking periods (I wasn't sure if it's necessary before, but now that we established that at least 2 of those periods will be quite important I just decided to list all of them)
:+1:
> Prompts for setting api URI for the first time when not yet set
:+1:
> Improved missing account flow (+ added account:import suggestion)

I didn't see any changes here?

> Removed potentially confusing Opening ID from openings list (working-groups:openings)
:+1:
> Not showing 0x as default value (to avoid confusion)
:+1:
> working-groups:overview - now highlighting workers for which role keys are available in the CLI (excluding Alice and Bob)
:+1:
> Current group (name) is now logged in the console when executing working-groups-family commands
:+1:

Great work sir!
I'll mark as approve, as the improvements suggested are for now only cosmetic.

**Comment by Lezek123** [comment]
> It's a nice feature that you can save your createdOpenings as drafts, but it's not clear how I can use/edit the draft for later openings?

All this information should be available in `working-groups:createOpening --help`, but it's possible to add some hints here and there too.

> Improved missing account flow (+ added account:import suggestion)
> I didn't see any changes here?

If you have no accounts available and use command like ie. `working-groups:createOpening` - there should be a message saying that perhaps you should use `account:import` first. It's a minor change. Also previously when you had some account imported, but not "selected" (via `account:choose`), running this command would prompt for the account twice due to a minor bug, which should now be fixed.

**Pull request merged**
