### PR TITLE
Add curator to group extrinsic fix

### PR DESCRIPTION
**Pull request by iorveth**
Fix for https://github.com/Joystream/joystream/issues/1545
Based on: https://github.com/Joystream/joystream/pull/1542

### CODE REVIEW

**Comment by mnaamani** [comment]
I only reviewed https://github.com/Joystream/joystream/pull/1546/commits/11cdf19d71198157f06a6b187b97cfc7d231dd2e
Looks good. Will merge this after #1542

**Review by mnaamani — CHANGES_REQUESTED** [review]
Update from babylon branch to get new CI checks

**Review by mnaamani — APPROVED** [review]
LGTM

obv the 'Content Directory Initialization' CI check is failing because of the new `ClassOf` type introduced by refactoring. The `@joystream/types` will need to be updated in another PR.

**Comment by mnaamani** [comment]
@iorveth  could you merge updated babylon branch again, @Lezek123 added joystream/types fixes in #1556 so the checks should run again succesfully now.

**Comment by iorveth** [comment]
Done

**Comment by mnaamani** [comment]
The storage-node CI checks is failing in this job run. I suspect it is due ipns name publishing not completing in allotted time for the test. Will fix in another PR.
The important thing is the runtime intergartion test and content direct init tests are now passing.

**Pull request merged**
