### PR TITLE
Metaprotocol video comments and reactions

### PR DESCRIPTION
**Pull request by kdembler**

### CODE REVIEW

**Comment by mnaamani** [comment]
@zeeshanakram3 Please bump the `metadata-profobuf/package.json` version from `2.1.0` to `2.2.0` and maybe update the description to
`Joystream Metadata Protobuf Library` I don't think it makes sense to put the release name in there anymore.

**Comment by zeeshanakram3** [comment]
> @zeeshanakram3 Please bump the `metadata-profobuf/package.json` version from `2.1.0` to `2.2.0` and maybe update the description to `Joystream Metadata Protobuf Library` I don't think it makes sense to put the release name in there anymore.

Done in #3831

**Review by ondratra — APPROVED** [review]
I've reviewed the last 2 commits (including changes from #3781, #3793); the rest of the code was reviewed before. Looks good.

**Comment by mnaamani** [comment]
Currently doing a test sync against production network. Will report back if I find any issues.

**Pull request merged**
