### PR TITLE
Query node: Special handling for runtime proposal execution

### PR DESCRIPTION
**Pull request by Lezek123**
- Addresses https://github.com/Joystream/joystream/issues/3336
- Factors out common proposal status change logic to `setProposalStatus` function

### CODE REVIEW

**Review by ondratra — APPROVED** [review]
LGTM

**Comment by mnaamani** [comment]
Looks correct, testing it out.

**Comment by mnaamani** [comment]
Screen Shot 2022-03-04 at 2 55 38 PM

Had difficulty running the runtime upgrade proposal test:
I had to modify the `AllProposalsOutcomesFixture` to only create one additional proposal to be Approved. (I think it might be due to proposal locks not being unlocked)

The runtime upgrade is successful and as you can see above the first "to be cancelled" proposal did indeed get the correct status updated.
The integration tests still fail however:
```
  integration-tests:query-node-api:try:getProposalsByIds([this.params[i].proposalId]) Unexpected query result (expected 'ProposalStatusGracing' to equal 'ProposalStatusExecuted') +3s
  integration-tests:query-node-api:try:getProposalsByIds([this.params[i].proposalId]) Max number of query retries (12) reached! +0ms
  integration-tests:resources released Proposals +3m
  integration-tests:resources released Proposals +0ms
  integration-tests:resources released Proposals +0ms
  integration-tests:job:runtime upgrade proposal flow 0 failed: +4m
AssertionError: expected 'ProposalStatusGracing' to equal 'ProposalStatusExecuted'
    at DecideOnProposalStatusFixture.assertProposalExecutedAsExpected (/Users/mokhtar/joystream/joystream/tests/network-tests/src/fixtures/proposals/DecideOnProposalStatusFixture.ts:151:12)
    at /Users/mokhtar/joystream/joystream/tests/network-tests/src/fixtures/proposals/DecideOnProposalStatusFixture.ts:207:27
    at QueryNodeApi.tryQueryWithTimeout (/Users/mokhtar/joystream/joystream/tests/network-tests/src/QueryNodeApi.ts:367:9)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async /Users/mokhtar/joystream/joystream/tests/network-tests/src/fixtures/proposals/DecideOnProposalStatusFixture.ts:205:26
    at async Promise.all (index 0)
    at async DecideOnProposalStatusFixture.runQueryNodeChecks (/Users/mokhtar/joystream/joystream/tests/network-tests/src/fixtures/proposals/DecideOnProposalStatusFixture.ts:197:5)
    at async FixtureRunner.runQueryNodeChecks (/Users/mokhtar/joystream/joystream/tests/network-tests/src/Fixture.ts:198:5)
    at async FixtureRunner.runWithQueryNodeChecks (/Users/mokhtar/joystream/joystream/tests/network-tests/src/Fixture.ts:203:5) {
  showDiff: true,
  actual: 'ProposalStatusGracing',
  expected: 'ProposalStatusExecuted',
  operator: 'strictEqual'
}
  integration-tests:job:runtime upgrade proposal [Failed] +39ms
```

**Comment by mnaamani** [comment]
Its actually more likely that the grace period of the runtime upgrade is longer than the time the query lookup retries timeout that is causing the failure.

**Review by mnaamani — APPROVED** [review]

**Pull request merged**
