### PR TITLE
Content directory initialization helper

### PR DESCRIPTION
**Pull request by Lezek123**
This PR introduces an easier way to initialize the content directory.
Now it can be done with just:
```
import { initializeContentDir } from 'cd-schemas'

/* ... */
await initializeContentDir(api, LEAD_KEYRING_PAIR)
```

In order to get more flexibility, see `content-directory-schemas/src/helpers/initialize.ts` script for reference (it's just a few lines of code that can be customized with some custom extrinsic handlers etc.)

### CODE REVIEW

**Review by iorveth — APPROVED** [review]
LGTM!

**Comment by mnaamani** [comment]
So just for testing I added `cd-schemas` as dependency in `tests/network-tests/package.json` and added a method in the `tests/network-tests/src/Api.ts`

```
   import initializeContentDir from 'cd-schemas/helpers/initialize'

  public async initCD() {
    const contentLead = await this.getGroupLead(WorkingGroups.ContentDirectoryWorkingGroup)
    const leadKey = this.keyring.getPair(contentLead!.role_account_id)
    return initializeContentDir(this.api, leadKey)
  }
```

When I try to build I get:

```
src/Api.ts:33:34 - error TS2307: Cannot find module 'cd-schemas/helpers/initialize' or its corresponding type declarations.

33 import initializeContentDir from 'cd-schemas/helpers/initialize'
                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Found 1 error.
```

Would we need to add something in `tests/network-tests/tsconfig.json` or is something missing in `cd-schemas` pacakge?

**Comment by iorveth** [comment]
cc @mnaamani , here is a typo 

`import initializeContentDir from 'cd-schemas/helpers/initialize',`

use this instead 
`import initializeContentDir from 'cd-schemas/src/helpers/initialize'`

**Comment by mnaamani** [comment]
> cc @mnaamani , here is a typo
> 
> `import initializeContentDir from 'cd-schemas/helpers/initialize',`
> 
> use this instead
> `import initializeContentDir from 'cd-schemas/src/helpers/initialize'`

Ah good catch.

**Comment by mnaamani** [comment]
So that resolved one issue, now I get:

```
MokoBook:network-tests mokhtar$ yarn checks
yarn run v1.22.4
$ tsc --noEmit --pretty && prettier ./ --check && yarn lint
../../content-directory-schemas/src/helpers/InputParser.ts:73:40 - error TS2339: Property 'name' does not exist on type 'Codec'.

73       this.classIdByNameMap.set(aClass.name.toString(), (key.args[0] as ClassId).toNumber())
                                          ~~~~

../../content-directory-schemas/src/helpers/InputParser.ts:87:11 - error TS2322: Type '[EntityId, Codec][]' is not assignable to type '[EntityId, Entity][]'.
  Type '[EntityId, Codec]' is not assignable to type '[EntityId, Entity]'.
    Type 'Codec' is missing the following properties from type 'Entity': entity_permissions, class_id, supported_schemas, values, and 21 more.

87     const entityEntries: [EntityId, Entity][] = (
             ~~~~~~~~~~~~~


Found 2 errors.
```

Did I forget to fetch latest commit ?

**Review by mnaamani — APPROVED** [review]

**Comment by mnaamani** [comment]
Just leaving a note with latest fix the proper way to import is now:

`import { initializeContentDir } from 'cd-schemas'`

**Pull request merged**
