### PR TITLE
Forum internal actors

### PR DESCRIPTION
**Pull request by ondratra**
related to #762

### CODE REVIEW

**Review by bedeho — CHANGES_REQUESTED** [review]
Well done, however there is room for improvement in crafting a better logical unit of work.

You do not give any real scope in the PR description, so I can only go by the title, however, you are inconsistently treating the removal of different roles, any there is no obvious reason why. The lead seems to be removed entirely, the user type has quite a lot removed - but there is still for example the event `ForumUserCreated`, and there is no user authentication introduced, and the moderator type is entirely untouched. 

You could have sliced this many different ways, the simplest would just be to only fix the concept of sudo and lead, however you went beyond this in an inconsistent way, so its hard to evaluate what is going on.

Please try to refract the PR scope text to match some better unit of work, and update the work outstanding.

**Comment by ondratra** [comment]
This PR was marked probably sooner than it should, sorry for that. 

Changes focus on module sections of #762. The internal representation of forum user, moderator, and sudo were removed. Most of the code is reusing old concepts of sudo, as you mentioned. Important functions [ensure_is_forum_sudo](https://github.com/Joystream/joystream/pull/827/files#diff-5c3c034195f94c91f269a928d62e410cL1967), `ensure_is_forum_member_with_correct_account`, `ensure_is_moderator_with_correct_account` were reimplemented while connections to the rest of the code were (mostly) retained.

I am not sure what the authentication mechanism should be. I thought the point of [is_lead](https://github.com/Joystream/joystream/blob/375896fc6941e70a323c1993ce031d13daf03483/runtime-modules/forum/src/lib.rs#L287), `is_moderator`, and `is_forum_member` is to delegate checks for user privileges and authentication itself to external code. Right now module excepts that runtime has its own representation of user ids, etc. and passes it to module's actions like [add_post(origin, formUserId, ...)](https://github.com/Joystream/joystream/blob/375896fc6941e70a323c1993ce031d13daf03483/runtime-modules/forum/src/lib.rs#L1250)

`ForumUserCreated` is removed now as well as moderator (see 2 latest commits).

**Review by bedeho — CHANGES_REQUESTED** [review]
Looks goods, only a few minor things now.

- We are repeating ourselves a lot in the authentication. Its always to steps
1. check origin is signed
2. check that signer account and possible id is who they claim they are

- Can we rename `ensure_is_forum_member_with_correct_account` to `ensure_is_forum_user`.

- Can we rename `ensure_is_moderator_with_correct_account` to `ensure_is_moderator`.



can we just combine this into a single check, for each role of course, which just takes the origin and returns both the account (which is almost always ignored), and the underlying

**Review by bedeho — APPROVED** [review]
Perfect!

**Pull request merged**
