### PR TITLE
Docker apps fixes

### PR DESCRIPTION
**Pull request by mnaamani**
Some additional fixes following: https://github.com/Joystream/joystream/pull/2167

Implements: https://github.com/Joystream/joystream/issues/2217 and long pending issue: https://github.com/Joystream/joystream/issues/1541

Fixes build.sh, start.sh and query-node/run-tests.sh scripts and overall docker image build to get one click dev setup working again, and integration tests (by removing old content directory tests).

Only thing broken which needs an update in hydra-cli is in the generated `generated/graphql-server/package.json`

```
  "dependencies": {
    "dotenv": "^8.2.0",
    "reflect-metadata": "^0.1.13",
    "warthog": "https://github.com/metmirr/warthog/releases/download/v2.23.0/warthog-v2.23.0.tgz",
    "@types/bn.js": "^4.11.6",
    "bn.js": "^5.1.3"
  },
  "devDependencies": {
    "@types/jest": "^24.0.23",
    "dotenvi": "^0.9.0",
    "jest": "^24.9.0",
    "ts-jest": "^24.1.0",
    "ts-node": "^8.10",
    "ts-node-dev": "^1.0.0-pre.60",
    "typescript": "^3.9.7"
  },
```

`dotenvi`, and `ts-node` need to be moved from `devDependencies` to `dependencies` because they are in-fact not dev dependencies but are needed in production.

Note how I had to move the dependencies in root `query-node/package.json` into correct dependencies:
```
    "@dzlzv/hydra-cli": "2.0.0-beta",
    "@dzlzv/hydra-processor": "0.1.1"
```
Because they are used in production also.

### CODE REVIEW

**Comment by dzhelezov** [comment]
From now on all hydra packages (including Docker images) are going to have the same version. The current is 2.0.1-beta.3 and is tagged ‘next’. Perhaps we can have a single variable defined somewhere to ease version bumps? Or just refer by ‘next’ or ‘latest’ ?

**Comment by dzhelezov** [comment]
A couple more comments for `docker-compose.yml`:
- `PROCESSOR_POLL_INTERVAL` (how often the processor polls the indexer) is a processor setting, not indexer's
- (Not strict) In the `indexer` service: TYPES_JSON is a path within the container, so it'd be more natural to set it to `types.json` and map the volume: as `<host path>: /home/hydra/packages/hydra-indexer/types.json`.

**Comment by mnaamani** [comment]
> next

I think `latest` is the convention for docker images so that might be best choice.

**Comment by mnaamani** [comment]
> A couple more comments for `docker-compose.yml`:
> 
>     * `PROCESSOR_POLL_INTERVAL` (how often the processor polls the indexer) is a processor setting, not indexer's
> 
>     * (Not strict) In the `indexer` service: TYPES_JSON is a path within the container, so it'd be more natural to set it to `types.json` and map the volume: as `<host path>: /home/hydra/packages/hydra-indexer/types.json`.

Thanks for the review. Applied suggestions in 2c5c28b706ef53590a57403446bc7b986e324ab1

**Review by ondratra — APPROVED** [review]
LGTM! Docker compose compiled, and run everything except the processor, which is to be expected.

**Pull request merged**
