### PR TITLE
Forum v2 migration

### PR DESCRIPTION
**Pull request by iorveth**
This PR aims to: 
1. migrate `forum_v2` to the substrate 2.0.0 version. (both core logic and tests)
1. integrate forum v2 into the node runtime
1. adjust test coverage for newly introduced forum working group (Instance1)

### CODE REVIEW

**Review by shamil-gadelshin — CHANGES_REQUESTED** [review]
There are some linter issues on running the 'cargo clippy' command. 
We use the recommended version from Parity for the rust compiler: 'nightly-2020-10-06'.

Also, there are multiple compilation errors on testing.

**Comment by iorveth** [comment]
> There are some linter issues on running the 'cargo clippy' command.
> We use the recommended version from Parity for the rust compiler: 'nightly-2020-10-06'.
> 
> Also, there are multiple compilation errors on testing.

Done

**Review by shamil-gadelshin — CHANGES_REQUESTED** [review]
Everything looks good. Several comments:
- please, confirm with @bedeho that we should remove migration logic. And if not, consider migrating code in the 'misc' folder to the latest Substrate version.
- remove the commented code from the lib.rs and test.rs
- change some comments from regular to doc-comments in the event and error macros
- confirm that InputValidationLengthConstraint is equal to the version from common and remove it
- remove the invalid module comment from the lib.rs
**UPD:** - bump the forum crate version to the 4.0.0

**Comment by iorveth** [comment]
> * module

Fixed all points, except of 
`- confirm that InputValidationLengthConstraint is equal to the version from common and remove it`
It should be completely removed in further forum PR https://github.com/Joystream/joystream/pull/1755

**Review by shamil-gadelshin — CHANGES_REQUESTED** [review]
Compilation errors on testing.

**Comment by iorveth** [comment]
> Compilation errors on testing.

Fixed

**Review by shamil-gadelshin — APPROVED** [review]
LGTM

**Pull request merged**
