### PR TITLE
Substrate version upgrade into iznik branch (Alexandria)

### PR DESCRIPTION
**Pull request by mnaamani**
Merge [substrate_version-upgrade](https://github.com/Joystream/joystream/tree/substrate_version_upgrade) branch into iznik, fixing merge conflicts.

Additional Fixes:
- [x] substrate-test-runtime custom build script failing in VScode/IDE environment (in similar way to runtime build.rs?)
   With RLS extension enabled in IDE this causes constant high CPU as it keeps trying to rebuild.
Source `sc-service-test` package used in tests: `node/src/chain_spec.rs` and `node/src/service.rs`

https://github.com/paritytech/substrate/blob/master/test-utils/runtime/build.rs
```
build failed
error: failed to run custom build command for `substrate-test-runtime v2.0.0-rc4 (https://github.com/paritytech/substrate.git?rev=00768a1f21a579c478fe5d4f51e1fa71f7db9fd4#00768a1f)`

Caused by:
  process didn't exit successfully: `/Users/mokhtar/joystream/joystream/target/rls/debug/build/substrate-test-runtime-963dba27e2a1de0d/build-script-build` (exit code: 1)
--- stdout
Unknown argument 'run'. Supported arguments:

    --version or -V to print the version and commit info
    --help or -h for this message
    --cli starts the RLS in command line mode
    No input starts the RLS as a language server
    
```

- [x] Travis CI Build not completing, while building with command: ` BUILD_DUMMY_WASM_BINARY=1 cargo test --release --verbose --all` seems to stall while building `Running rustc --crate-name joystream_node...`

```
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.

Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#build-times-out-because-no-output-was-received

The build has been terminated
```

The issues haven't been fixed, only work around for now.
https://github.com/Joystream/joystream/pull/1163#issuecomment-675319740 for IDE/RLS issue
unit test code was commented out for now.

### CODE REVIEW

**Comment by mnaamani** [comment]
Workaround for `substrate-test-runtime` custom build failing, set `BUILD_DUMMY_WASM_BINARY=1` env variable when opening your IDE:

`BUILD_DUMMY_WASM_BINARY=1 code ./joystream`

or

`BUILD_DUMMY_WASM_BINARY=1 atom ./joystream`

**Comment by mnaamani** [comment]
I changed `cargo test --all` to `cargo test` thinking maybe the integration tests which are tagged as `ignore` are somehow running in the background, but the build still stalls at:

`Compiling sc-service-test v2.0.0-rc4 (https://github.com/paritytech/substrate.git?rev=00768a1f21a579c478fe5d4f51e1fa71f7db9fd4#00768a1f)`

So should we disable these tests altogether?

**Comment by mnaamani** [comment]
Trying build [without node tests](f4c1898ce6707210f3c21f8d7b7950c2d6365056) in https://github.com/Joystream/joystream/pull/1175

**Review by shamil-gadelshin — APPROVED** [review]
LGTM. 

Travis CI fails with an error during the frame-support compilation.
Here is the discussion: https://github.com/paritytech/substrate/issues/6167

We could pin the exact nightly toolchain to the 1.45.0 version.

**UPD:** We'd already encountered that issue - (https://github.com/Joystream/joystream/issues/495) and we even have a proper rust version.

**Comment by mnaamani** [comment]
> LGTM.
> 
> Travis CI fails with an error during the frame-support compilation.
> Here is the discussion: [paritytech/substrate#6167](https://github.com/paritytech/substrate/issues/6167)
> 
> We could pin the exact nightly toolchain to the 1.45.0 version.
> 
> **UPD:** We'd already encountered that issue - (#495) and we even have a proper rust version.

As discussed I reverted back to working nightly version `nightly-2020-05-23`

**Pull request merged**
