### PR TITLE
Handling of decimal points

### PR DESCRIPTION
**Pull request by DzhideX**
Implement changes from issue #1300.

### CODE REVIEW

**Review by Lezek123 — APPROVED** [review]
Great, nicely spotted!
The issue seems to have been caused by `new BN(basePower + siUnitPower - modString.length)` returning negative number, which happens if more decimal numbers are specified than expected (in case of our chain - any decimals at all)

Possible further improvements:
- Add a comment explaining this, so anyone running into those commented-out lines in the future can understand the reason immediately.
- Alternatively: Block the user from from providing more decimals than expected

**Comment by bwhm** [comment]
> Great, nicely spotted!
> The issue seems to have been caused by `new BN(basePower + siUnitPower - modString.length)` returning negative number, which happens if more decimal points are specified than expected (in case of our chain - any decimal points at all)
> 
> Possible further improvements:
> 
>     * Add a comment explaining this, so anyone running into those commented-out lines in the future can understand the reason immedietaly.
> 
>     * Alternatively: Block the user from from providing more decimal points than expected

I'd love to merge this, but the build fails :(
Any ideas @Lezek123 @mnaamani ?

I seem to remember this has been a recurring problem, and maybe a problem with the testing - not the PR?

**Review by bwhm — APPROVED** [review]
Tested a while back, and it worked :)

**Comment by Lezek123** [comment]
> I'd love to merge this, but the build fails :(
> Any ideas @Lezek123 @mnaamani ?

There is no additional information in https://github.com/Joystream/joystream/pull/1421/checks?check_run_id=1140518902, so I suspect it's some temporary github CI issue. Perhaps @mnaamani can re-run the checks to verify.

**Comment by mnaamani** [comment]
> > I'd love to merge this, but the build fails :(
> > Any ideas @Lezek123 @mnaamani ?
> 
> There is no additional information in https://github.com/Joystream/joystream/pull/1421/checks?check_run_id=1140518902, so I suspect it's some temporary github CI issue. Perhaps @mnaamani can re-run the checks to verify.

Yes Mac Issue as usual, running the tests again

**Pull request merged**
