### PR TITLE
Giza: Update Hydra, remove ManyToMany "assignment" workaround

### PR DESCRIPTION
**Pull request by Lezek123**
- Updates Hydra to `3.1.0-alpha.13` to fix issues with `Connection` query filtering
- Adds `ManyToMany` relationships `postinstall` fix (analogous to the one in https://github.com/Joystream/joystream/pull/2822)
- Removes `ManyToMany` workaround in storage v2 schemas (`StorageBagStorageAssignment`, `StorageBagDistributionAssignment`)

### CODE REVIEW

**Review by shamil-gadelshin — APPROVED** [review]
Looks good.

I tested ManyToMany for the StorageBags. It worked as expected.

**Comment by mnaamani** [comment]
I tried merging this into giza_staging for testing but I get issue when running query-node at db migration step:

```
$ yarn db:schema:migrate && yarn db:processor:migrate
$ yarn workspace query-node db:migrate
$ warthog db:migrate
Error: Command failed: /joystream/query-node/generated/graphql-server/node_modules/.bin/ts-node /joystream/query-node/generated/graphql-server/node_modules/.bin/typeorm migration:run  --config generated/ormconfig.ts 
Error: Cannot find module '/joystream/query-node/generated/graphql-server/node_modules/.bin/typeorm'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at main (/joystream/query-node/generated/graphql-server/node_modules/ts-node/src/bin.ts:227:14)
    at Object.<anonymous> (/joystream/query-node/generated/graphql-server/node_modules/ts-node/src/bin.ts:513:3)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)

    at ChildProcess.exithandler (child_process.js:383:12)
    at ChildProcess.emit (events.js:400:28)
    at maybeClose (internal/child_process.js:1058:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:293:5) {
  killed: false,
  code: 1,
  signal: null,
  cmd: '/joystream/query-node/generated/graphql-server/node_modules/.bin/ts-node /joystream/query-node/generated/graphql-server/node_modules/.bin/typeorm migration:run  --config generated/ormconfig.ts ',
  stdout: '',
  stderr: "Error: Cannot find module '/joystream/query-node/generated/graphql-server/node_modules/.bin/typeorm'\n" +
    '    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)\n' +
    '    at Function.Module._load (internal/modules/cjs/loader.js:746:27)\n' +
    '    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)\n' +
    '    at main (/joystream/query-node/generated/graphql-server/node_modules/ts-node/src/bin.ts:227:14)\n' +
    '    at Object.<anonymous> (/joystream/query-node/generated/graphql-server/node_modules/ts-node/src/bin.ts:513:3)\n' +
    '    at Module._compile (internal/modules/cjs/loader.js:1085:14)\n' +
    '    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)\n' +
    '    at Module.load (internal/modules/cjs/loader.js:950:32)\n' +
    '    at Function.Module._load (internal/modules/cjs/loader.js:790:12)\n' +
    '    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)\n'
}
$ hydra-processor migrate --env ../.env
INFO: Running migrations for Hydra Processor
INFO: Hydra Processor migrations completed successfully
```

I saw yarn.lock changed on build of query-node, maybe that is somehow related. 

Will investigate further.

**Comment by Lezek123** [comment]
> I tried merging this into giza_staging for testing but I get issue when running query-node at db migration step:

Should be fixed in https://github.com/Joystream/joystream/pull/2847/commits/f90e516a5df379e3449db2909b5710132150cc73

**Comment by mnaamani** [comment]
> > I tried merging this into giza_staging for testing but I get issue when running query-node at db migration step:
> 
> Should be fixed in [f90e516](https://github.com/Joystream/joystream/commit/f90e516a5df379e3449db2909b5710132150cc73)

That solved it. I remember we did have this workaround not sure when it was removed.

**Review by mnaamani — APPROVED** [review]
Fancy way of patching hydra code :) Although I hope hydra team can patch it upstream in future.
Tested that it builds and runs successfully.
Tested on giza-staging as well.
Will go by Shamil's testing of the actual query works as intended.

**Pull request merged**
