### PR TITLE
Add initial invitation balance to `MemberInvited` event, remove workaround, bring back tests

### PR DESCRIPTION
**Pull request by Lezek123**
Addresses https://github.com/Joystream/joystream/issues/4643
- **Runtime:** add initial invitation balance to `MemberInvited` event
- **Query node:** remove hardcoded initial invitation balance and add the new property to `MemberInvitedEvent`
- **Integration tests:** Bring back the tests originally introduced in https://github.com/Joystream/joystream/pull/4533 (with adjustments due to sudo module removal)

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202078489349362/1204004850546542) by [Unito](https://www.unito.io)

### CODE REVIEW

**Review by zeeshanakram3 — APPROVED** [review]
LGTM.

**Review by mnaamani — CHANGES_REQUESTED** [review]
Looks good, I like that the tests change the invitation balance is updated twice between invites.
Only change request would be to bump types package version to `v2.1.0` since we already published `2.0.0` to npm.

**Comment by Lezek123** [comment]
> Only change request would be to bump types package version to v2.1.0 since we already published 2.0.0 to npm.

https://github.com/Joystream/joystream/pull/4646/commits/f899922645013cd5aad6d8036aeae2180f123cf7

I bumped types to `2.1.0`, but since only QN depends on this change I only bumped the dependency there.
Other packages depend on `^2.0.0`, so will use the monorepo version as well.
The only exception was `@joystream/js`, so I changed the types dependency from `~2.0.0` to `^2.0.0` there.

**Review by mnaamani — APPROVED** [review]

**Comment by mnaamani** [comment]
> The only exception was `@joystream/js`, so I changed the types dependency from `~2.0.0` to `^2.0.0` there.

So just to confirm, there is no need to publish a new version of `@joystream/js` as it doesn't care about the MemberInvited event changes?

**Comment by Lezek123** [comment]
> So just to confirm, there is no need to publish a new version of @joystream/js as it doesn't care about the MemberInvited event changes?

Yes, it doesn't depend on those changes. The only inconvinience would be if someone tries to use `@joystream/js` together with `@joystream/types@2.1.0`, as then they would end up with either 2 versions of types (`2.0.0` and `2.1.0` since `@joystream/js` depended on `~2.0.0` the last time it was released), or they would have to use `resolutions`/`overrides`.

**Comment by mnaamani** [comment]
FYI @thesan https://www.npmjs.com/package/@joystream/types/v/2.1.0

**Pull request merged**
