### PR TITLE
Forum thread tags (runtime part)

### PR DESCRIPTION
**Pull request by iorveth**
Partially closes https://github.com/Joystream/joystream/issues/2422 (runtime part)

### CODE REVIEW

**Review by Lezek123 — COMMENTED** [review]
Looks good, I didn't encounter any issues when updating query-node and tests.
I noticed there are a few places where title is still referenced, for example:
- `ensure_can_edit_thread_title`
- `good_thread_title`

But this is probably ok, considering that metadata is `title` + optionally some `tags`.

I was also wondering about the `title_hash` -> `metadata_hash` change.
I'm not sure if storing the `metadata_hash` is of any use at this point, because metadata updates can be partial and since the runtime is not aware of this, it will just store the lastest metadata update hash in this field, which can be confusing. Can we just drop the hash? Does this affect any planned functionality?

**Comment by bedeho** [comment]
> I was also wondering about the title_hash -> metadata_hash change.
I'm not sure if storing the metadata_hash is of any use at this point, because metadata updates can be partial and since the runtime is not aware of this, it will just store the lastest metadata update hash in this field, which can be confusing. Can we just drop the hash? Does this affect any planned functionality?

I agree, lets drop.

**Comment by iorveth** [comment]
> > I was also wondering about the title_hash -> metadata_hash change.
> > I'm not sure if storing the metadata_hash is of any use at this point, because metadata updates can be partial and since the runtime is not aware of this, it will just store the lastest metadata update hash in this field, which can be confusing. Can we just drop the hash? Does this affect any planned functionality?
> 
> I agree, lets drop.

Done

**Comment by shamil-gadelshin** [comment]
Changed base branch to `olympia` because `olympia_dev` is deprecated.

**Review by bedeho — APPROVED** [review]

**Pull request merged**
