### PR TITLE
Giza: zero storage fees

### PR DESCRIPTION
**Pull request by mnaamani**
Make the storage deletion prize 0.

### CODE REVIEW

**Review by dobertRowneySr — APPROVED** [review]

**Review by shamil-gadelshin — CHANGES_REQUESTED** [review]
We need to change the version in the `runtime/lib.rs` as well.

**Comment by mnaamani** [comment]
Despite the change I still see the error `InsufficientBalance` from the storage system.
Can it possibly be due to the rounding up to nearest greater integer?


```
// Calculate data storage fee based on size. Fee-value uses megabytes as measure value.
    // Data size will be rounded to nearest greater MB integer.
    pub(crate) fn calculate_data_storage_fee(bytes: u64) -> BalanceOf<T> {
        let mb_fee = Self::data_object_per_mega_byte_fee();

        const ONE_MB: u64 = 1_048_576;

        let mut megabytes = bytes / ONE_MB;

        if bytes % ONE_MB > 0 {
            megabytes += 1; // rounding to the nearest greater integer
        }

        mb_fee.saturating_mul(megabytes.saturated_into())
    }
```

**Comment by mnaamani** [comment]
> We need to change the version in the `runtime/lib.rs` as well.

Oh yes I totally missed that :D ty

**Comment by mnaamani** [comment]
> Despite the change I still see the error `InsufficientBalance` from the storage system. Can it possibly be due to the rounding up to nearest greater integer?
> 
> ```
> // Calculate data storage fee based on size. Fee-value uses megabytes as measure value.
>     // Data size will be rounded to nearest greater MB integer.
>     pub(crate) fn calculate_data_storage_fee(bytes: u64) -> BalanceOf<T> {
>         let mb_fee = Self::data_object_per_mega_byte_fee();
> 
>         const ONE_MB: u64 = 1_048_576;
> 
>         let mut megabytes = bytes / ONE_MB;
> 
>         if bytes % ONE_MB > 0 {
>             megabytes += 1; // rounding to the nearest greater integer
>         }
> 
>         mb_fee.saturating_mul(megabytes.saturated_into())
>     }
> ```

of course it cannot be that lol, as long as mb_fee is zero. Most likely I was running wrong runtime because I didn't bump the version as pointed out.

**Comment by mnaamani** [comment]
Ok thanks for helping with debugging @shamil-gadelshin the issue was that in my test environment I had forgotten to set the data fee to zero. Atlas works now with new membership with 0 balance.

**Review by shamil-gadelshin — APPROVED** [review]
LGTM

**Pull request merged**
