### PR TITLE
Forum 2

### PR DESCRIPTION
**Pull request by ondratra**
Draft for new forum; solving issues #759 & #766.

### CODE REVIEW

**Comment by mnaamani** [comment]
The runtime build CI check is failing because of bad formatting. We have git hooks configured which don't seem to be running on your side.

Try running `yarn` in the root folder it should install all dependencies including husky which will setup and configure the githooks.

If that fails you can try to do `yarn cargo-checks` to see what's wrong.

To fix formatting issues, you can just run `cargo fmt --all`

**Comment by ondratra** [comment]
@mnaamani Thanks for the info about `yarn`. Maybe we should introduce info about the necessity of running `yarn` command in root to the documentation as there doesn't seem to be a mention about it right now? I've also noticed before that Travis is using `cargo clippy` in addition to `cargo fmt --all`. 

Btw: Travis builds fail on compile errors, not the formatting errors (except the last commit where I introduced one formatting error you've noticed). I'm still solving those errors.

**Comment by mnaamani** [comment]
Thanks for the update @ondratra I will make a note of updating the instructions in README

**Comment by mnaamani** [comment]
> Travis is using `cargo clippy` in addition to `cargo fmt --all`

Correct. If you run `yarn cargo-checks` it will also do both formatting and clippy checks

**Pull request merged**
