### PR TITLE
Iznik cleanup

### PR DESCRIPTION
**Pull request by DzhideX**
Implementing all the tasks from Issue #1405 .

### CODE REVIEW

**Review by Lezek123 — APPROVED** [review]
Looks good

**Comment by mnaamani** [comment]
I redirected this PR to master branch

**Comment by bwhm** [comment]
@mnaamani 
Should we merge this now?

**Comment by bwhm** [comment]
Actually, before merging, let's wait for the final point on this #1405  that I re-introduced.

For future reference @DzhideX , please refer to the issue your PR is addressing if applicable :)

**Comment by bwhm** [comment]
@mnaamani @Lezek123 
Can we merge this now?

**Comment by Lezek123** [comment]
> @mnaamani @Lezek123
Can we merge this now?

Sure (unless the Netfliy `env` is still set to build maintenance page on merge or something, which shouldn't be the case?)  @mnaamani

**Comment by mnaamani** [comment]
> > @mnaamani @Lezek123
> > Can we merge this now?
> 
> Sure (unless the Netfliy `env` is still set to build maintenance page on merge or something, which shouldn't be the case?) @mnaamani

No we are already building from master and the env var is set correctly. Its good to merge.

**Pull request merged**
