### PR TITLE
Content migration script: Wait for finalization, improve error handling and logging

### PR DESCRIPTION
**Pull request by Lezek123**
- Wait until `utility.batch` tx is finalized before processing the result and uploading the objects
- Graceful exit: Make sure pending transactions are finalized and processed by the script before saving the state and exiting (after recieving an exit signal like `CTRL + C`)
- Add handling for `BatchInterrupted` case (for example: insufficient balance on sudo account)
- Improve logging: use `winson` for logging, add more messages

### CODE REVIEW

**Comment by mnaamani** [comment]
LGTM
Tested successfully with happy case.
Need to do a few more looks good, I need to do a few more "failure scenario" tests.

**Comment by mnaamani** [comment]
I tried to be a bit brutal in my testing for failed uploads retry. While the script was re-uploading I forcefully killed the storage node. Then after trying again it seems the tmp file had been already deleted.

```
cat results/sumer-giza/videosMigrationFailedUploads_1641544682011.json 
["dynamic:channel:1|2","dynamic:channel:1|3","dynamic:channel:1|4","dynamic:channel:1|5","dynamic:channel:1|6","dynamic:channel:1|7","dynamic:channel:1|8","dynamic:channel:1|9","dynamic:channel:1|10","dynamic:channel:1|11"]

migration-scripts sumer-giza:retryFailedUploads -f results/sumer-giza/videosMigrationFailedUploads_1641544682011.json
2022-01-07 09:37:16:3716 Assets Manager [info]: Uploading 10 data objects...
2022-01-07 09:37:20:3720 Assets Manager [error]: Upload of object 5 to http://localhost:3333 failed: write EPIPE
2022-01-07 09:37:20:3720 Assets Manager [error]: Upload of object 11 to http://localhost:3333 failed: write EPIPE
2022-01-07 09:37:20:3720 Assets Manager [error]: Upload of object 9 to http://localhost:3333 failed: write EPIPE
2022-01-07 09:37:20:3720 Assets Manager [error]: Upload of object 3 to http://localhost:3333 failed: write EPIPE
2022-01-07 09:37:20:3720 Assets Manager [error]: Upload of object 7 to http://localhost:3333 failed: write EPIPE
Done in 12.74s.

cat results/sumer-giza/videosMigrationFailedUploads_1641544682011.json 
["dynamic:channel:1|2","dynamic:channel:1|3","dynamic:channel:1|4","dynamic:channel:1|5","dynamic:channel:1|6","dynamic:channel:1|7","dynamic:channel:1|8","dynamic:channel:1|9","dynamic:channel:1|10","dynamic:channel:1|11"]

migration-scripts sumer-giza:retryFailedUploads -f results/sumer-giza/videosMigrationFailedUploads_1641544682011.json

yarn run v1.22.4
$ /root/dev/joystream-giza-staging/node_modules/.bin/migration-scripts sumer-giza:retryFailedUploads -f results/sumer-giza/videosMigrationFailedUploads_1641544682011.json
2022-01-07 09:38:40:3840 Assets Manager [info]: Uploading 10 data objects...
Error: Cannot upload object: 2: /tmp/joystream/sumer-giza-migration/gW4GEk3fUf5Qv6V4Mpm55EYvm2caQiyYRNPzyjwJwku8gH not found
    at AssetsManager.uploadDataObject (/root/dev/joystream-giza-staging/utils/migration-scripts/src/sumer-giza/AssetsManager.ts:238:13)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Promise.all (index 0)
    at AssetsManager.processQueuedUploads (/root/dev/joystream-giza-staging/utils/migration-scripts/src/sumer-giza/AssetsManager.ts:283:5)
    at RetryFailedUploadsCommand.run (/root/dev/joystream-giza-staging/utils/migration-scripts/src/commands/sumer-giza/retryFailedUploads.ts:44:7)
    at RetryFailedUploadsCommand._run (/root/dev/joystream-giza-staging/node_modules/@oclif/command/lib/command.js:43:20)
    at Config.runCommand (/root/dev/joystream-giza-staging/node_modules/@oclif/config/lib/config.js:173:24)
    at Main.run (/root/dev/joystream-giza-staging/node_modules/@oclif/command/lib/main.js:27:9)
    at Main._run (/root/dev/joystream-giza-staging/node_modules/@oclif/command/lib/command.js:43:20)
error Command failed with exit code 255.
```

It would be good to handle this case.

**Comment by mnaamani** [comment]
It seems the successfully upload files during the retry didn't get removed from the failed upload file.

**Comment by Lezek123** [comment]
> It seems the successfully upload files during the retry didn't get removed from the failed upload file.

Fixed in https://github.com/Joystream/joystream/pull/2989/commits/586b74401dc3f5d16b8058b8fd29fc24245ce71e
Now a new `unprocessedUploads_{timestamp}.json` file will be created for each `sumer-giza:migrateContent` / `sumer-giza:retryFailedUploads` run. The latest file will always have the most up-to-date state.

Additional changes to note:
- Video and channel migration now share a single `AssetsManager`, so failed/unprocessed uploads file will include both channel and video assets
- In case some asset cannot be downloaded from any storage provider, the script will terminate. This will prevent the script from creating video/channel with some of the assets missing, which was previously possible in that case

**Review by mnaamani — APPROVED** [review]

**Pull request merged**
