### PR TITLE
hydra-cli v0.0.22

### PR DESCRIPTION
**Pull request by mnaamani**

### CODE REVIEW

**Comment by metmirr** [comment]
There is an issue with this release, single entity queries are not working properly. I create a PR to fix the issue when Dmitrii releases the new version we can use that version.

**Comment by mnaamani** [comment]
> There is an issue with this release, single entity queries are not working properly. I create a PR to fix the issue when Dmitrii releases the new version we can use that version.

Yes I guess that explains the failed query-node integration tests failing with:

```
/home/runner/work/joystream/joystream/node_modules/@apollo/client/errors/index.js:26
        var _this = _super.call(this, errorMessage) || this;
                           ^
Error: Response not successful: Received status code 400
    at new ApolloError (/home/runner/work/joystream/joystream/node_modules/@apollo/client/errors/index.js:26:28)
    at /home/runner/work/joystream/joystream/node_modules/@apollo/client/core/QueryManager.js:484:19
```

It would probably be good idea to dump the error details @iorveth ?

**Comment by metmirr** [comment]
I tried to explain the issue here https://github.com/Joystream/hydra/pull/126. This bad request error is probably related to field names. The `hydra-cli v0.0.22` adds a new feature so I don't think Arsen uses this feature or maybe he is not sure about that :)

Can you share the query here?

**Comment by mnaamani** [comment]
Yes I think you are right, that error is probably related to the recent field name changes we made, and Arsen hasn't updated the tests. The query is looking for 'title' instead of 'handle' in the Channel:

https://github.com/Joystream/joystream/blob/babylon/tests/network-tests/src/Api.ts#L2042

**Comment by iorveth** [comment]
@mnaamani Hey, here is a PR, introducing the rest of query node & integration tests coverage and upgrades already  existing queries.  https://github.com/Joystream/joystream/pull/1654
It's currently based on babylon branch and hydra-cli 0.0.20, which have some issues?

@metmirr stated that `There is an issue with this release, single entity queries are not working properly`. 
Should i wait for the new hydra-cli release and update https://github.com/Joystream/joystream/pull/1654 afterwards?

**Comment by metmirr** [comment]
@iorveth single entity query allows you to query an entity with one of its unique fields. Currently, you are querying the created channel with the `channels(where: { handle_eq: "Example channel" })` and you get a result list. This new feature will allow you to do such queries `channel(where: { id: `1` })`, `category(where:{ name: "Film & Animation" })` and you will get a single entity back not a list. Since you are not using this feature there are no breaking changes for your tests. you can use `hydra-cli v0.0.22` version as well.

**Comment by mnaamani** [comment]
Replaced by https://github.com/Joystream/joystream/pull/1797

**Comment by mnaamani** [comment]
> @metmirr stated that `There is an issue with this release, single entity queries are not working properly`.
> Should i wait for the new hydra-cli release and update #1654 afterwards?

Yes that would be a good idea. I'll ping you when its ready

**Pull request closed without merging**
