### PR TITLE
Sumer content module tests

### PR DESCRIPTION
**Pull request by mnaamani**
Added test coverage and fixed a few bugs in content directory

### CODE REVIEW

**Review by iorveth — CHANGES_REQUESTED** [review]
Overall looks good! Though during the error cases testing you did not ensure that there is no event raised right after the call, wouldn`t it be beneficial to add this check? Here you can find an example for that assertion. https://github.com/Joystream/joystream/blob/olympia/runtime-modules/blog/src/tests.rs#L25

**Comment by mnaamani** [comment]
> Overall looks good! Though during the error cases testing you did not ensure that there is no event raised right after the call, wouldn`t it be beneficial to add this check? Here you can find an example for that assertion. https://github.com/Joystream/joystream/blob/olympia/runtime-modules/blog/src/tests.rs#L25

Interesting I had never thought of that. Will add.

**Comment by mnaamani** [comment]
> > Overall looks good! Though during the error cases testing you did not ensure that there is no event raised right after the call, wouldn`t it be beneficial to add this check? Here you can find an example for that assertion. https://github.com/Joystream/joystream/blob/olympia/runtime-modules/blog/src/tests.rs#L25
> 
> Interesting I had never thought of that. Will add.

So before doing this I wanted to check wether this assertion was redundant. So I made a small modification:
```
diff --git a/runtime-modules/content/src/lib.rs b/runtime-modules/content/src/lib.rs
index 80415d421..e1c20977e 100644
--- a/runtime-modules/content/src/lib.rs
+++ b/runtime-modules/content/src/lib.rs
@@ -638,6 +638,8 @@ decl_module! {
             actor: ContentActor<T::CuratorGroupId, T::CuratorId, T::MemberId>,
             params: ChannelCreationParameters<ContentParameters<T>, T::AccountId>,
         ) {
+            Self::deposit_event(RawEvent::ChannelCreatedFake);
+
             ensure_actor_authorized_to_create_channel::<T>(
                 origin,
                 &actor,
@@ -1460,6 +1462,7 @@ decl_event!(
         CuratorAdded(CuratorGroupId, CuratorId),
         CuratorRemoved(CuratorGroupId, CuratorId),
 
+        ChannelCreatedFake,
         // Channels
         ChannelCreated(
             ContentActor,
diff --git a/runtime-modules/content/src/tests/channels.rs b/runtime-modules/content/src/tests/channels.rs
index 106be4a06..4f31e3ee6 100644
--- a/runtime-modules/content/src/tests/channels.rs
+++ b/runtime-modules/content/src/tests/channels.rs
@@ -8,6 +8,8 @@ use frame_support::{assert_err, assert_ok};
 #[test]
 fn lead_cannot_create_channel() {
     with_default_mock_builder(|| {
+        let number_of_events_before_call = System::events().len();
+
         assert_err!(
             Content::create_channel(
                 Origin::signed(LEAD_ORIGIN),
@@ -20,6 +22,8 @@ fn lead_cannot_create_channel() {
             ),
             Error::<Test>::ActorCannotOwnChannel
         );
+
+        assert_eq!(System::events().len(), number_of_events_before_call);
     })
 }
```

The test passed, so it seems even if you `Self::deposit_event()` an event, and then the dispatch fails, events are not actually emitted.

So in-fact it is not necessary to assert that 0 events are emitted when a dispatch fails.

**Comment by iorveth** [comment]
> > > Overall looks good! Though during the error cases testing you did not ensure that there is no event raised right after the call, wouldn`t it be beneficial to add this check? Here you can find an example for that assertion. https://github.com/Joystream/joystream/blob/olympia/runtime-modules/blog/src/tests.rs#L25
> > 
> > 
> > Interesting I had never thought of that. Will add.
> 
> So before doing this I wanted to check wether this assertion was redundant. So I made a small modification:
> 
> ```
> diff --git a/runtime-modules/content/src/lib.rs b/runtime-modules/content/src/lib.rs
> index 80415d421..e1c20977e 100644
> --- a/runtime-modules/content/src/lib.rs
> +++ b/runtime-modules/content/src/lib.rs
> @@ -638,6 +638,8 @@ decl_module! {
>              actor: ContentActor<T::CuratorGroupId, T::CuratorId, T::MemberId>,
>              params: ChannelCreationParameters<ContentParameters<T>, T::AccountId>,
>          ) {
> +            Self::deposit_event(RawEvent::ChannelCreatedFake);
> +
>              ensure_actor_authorized_to_create_channel::<T>(
>                  origin,
>                  &actor,
> @@ -1460,6 +1462,7 @@ decl_event!(
>          CuratorAdded(CuratorGroupId, CuratorId),
>          CuratorRemoved(CuratorGroupId, CuratorId),
>  
> +        ChannelCreatedFake,
>          // Channels
>          ChannelCreated(
>              ContentActor,
> diff --git a/runtime-modules/content/src/tests/channels.rs b/runtime-modules/content/src/tests/channels.rs
> index 106be4a06..4f31e3ee6 100644
> --- a/runtime-modules/content/src/tests/channels.rs
> +++ b/runtime-modules/content/src/tests/channels.rs
> @@ -8,6 +8,8 @@ use frame_support::{assert_err, assert_ok};
>  #[test]
>  fn lead_cannot_create_channel() {
>      with_default_mock_builder(|| {
> +        let number_of_events_before_call = System::events().len();
> +
>          assert_err!(
>              Content::create_channel(
>                  Origin::signed(LEAD_ORIGIN),
> @@ -20,6 +22,8 @@ fn lead_cannot_create_channel() {
>              ),
>              Error::<Test>::ActorCannotOwnChannel
>          );
> +
> +        assert_eq!(System::events().len(), number_of_events_before_call);
>      })
>  }
> ```
> 
> The test passed, so it seems even if you `Self::deposit_event()` an event, and then the dispatch fails, events are not actually emitted.
> 
> So in-fact it is not necessary to assert that 0 events are emitted when a dispatch fails.

Good point, was not aware of that behaviour

**Review by iorveth — APPROVED** [review]
LGTM!

**Pull request merged**
