### PR TITLE
refs #849 reload free navigation menu

### LINKED ISSUE #840: Reload free navigation menu
When using Pioneer, any click on the navigation menu results in an extremely slow full page reload, which leaves the screen blank for 1s+. 

We could at least do slightly better by not reloading the menu all the time, and also show a proper spinner in place of the page loading, rather than an empty blank content area.

### PR DESCRIPTION
**Pull request by Dimitreee**
**Unnecessary Suspense children moved outside, PageComponent now only affected by Suspense.** 
Resolves #840 

(Pls provide more clientside issues)

### CODE REVIEW

**Comment by Dimitreee** [comment]
https://travis-ci.org/github/Joystream/joystream/builds/728776789 mhm..

**Comment by Dimitreee** [comment]
"No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself."

Can someone, please, relaunch pipeline?

**Comment by mnaamani** [comment]
Could you also update this PR from master.

**Comment by Dimitreee** [comment]
Cannot reproduce in master, issue and pr is not relevant.

**Comment by Dimitreee** [comment]
Cannot reproduce in master, issue and pr are not relevant.

**Pull request closed without merging**
