### PR TITLE
Refactoring of the working group integration with other pallets.

### PR DESCRIPTION
**Pull request by shamil-gadelshin**
### Affected pallets
- storage
- forum
- content-directory

#### Changes
- added `WorkingGroupIntegration` member to the pallets
- changed existing methods to use `WorkingGroupIntegration` trait.

[Main issue](https://github.com/Joystream/joystream/issues/1884)

### CODE REVIEW

**Review by iorveth — APPROVED** [review]
Awesome work, @shamil-gadelshin. 

I saw you only upgraded content-directory pallet version, don`t we need to do the same with the rest of the affected pallets?

**Comment by shamil-gadelshin** [comment]
> I saw you only upgraded content-directory pallet version, don`t we need to do the same with the rest of the affected pallets?

I had upgraded other affected pallets in bulk to version 4.0.0 previously. After the benchmarking, we could upgrade them to 4.0.1.

**Comment by iorveth** [comment]
Ok, great

**Comment by bedeho** [comment]
My extra pair of eyes are not needed here, so just merging.

**Pull request merged**
