### PR TITLE
Update hydra dependencies to 5.0.0-alpha.4

### PR DESCRIPTION
**Pull request by Lezek123**
Update dependencies to include the latest hydra fix: https://github.com/Joystream/hydra/pull/521

### CODE REVIEW

**Review by zeeshanakram3 — APPROVED** [review]
LGTM.

**Comment by Lezek123** [comment]
There seems to be some processing issue as https://github.com/Joystream/joystream/actions/runs/4627444652/jobs/8189300037?pr=4731 repeatedly fails.
To be further investigated, marking PR as draft for now.

**Comment by Lezek123** [comment]
I think the issue is that `storageSync` test produces a large amount of events in a single block, while currently we have a limit of the hydra processor event queue size set to `400` events.

Because of the way I implemented the fix in Hydra, in case the number of events in a block exceeds 400, the processor will be stuck waiting for all the events in a given block to be fetched from the indexer, which will never happen, because no new events will be fetched once the queue is full.

I will need to adjust my fix to take this into account.

**Comment by mnaamani** [comment]
Looks good.
I will address the failing runtime_upgrade integration test in https://github.com/Joystream/joystream/pull/4744

**Review by mnaamani — APPROVED** [review]
LGTM, deployed to production (backup cluster) synced without issues.
I changed base branch to master.

**Pull request merged**
