### PR TITLE
Olympia fix nft issuance variant added

### LINKED ISSUE #3277: Add BuyNow as initial state of NFT
# Update the types library as well!!

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201709380879215/1201858538808067) by [Unito](https://www.unito.io)

### PR DESCRIPTION
**Pull request by dobertRowneySr**
fixes #3277 

**EDIT**:
Due to latest discussion with @kdembler & @bedeho, in case of reward account not available we decided to:
- fallback to channel owner for member owner account
- throw error for curator owner account

### CODE REVIEW

**Review by kdembler — COMMENTED** [review]
Looks good to me feature-wise 👍

**Review by shamil-gadelshin — CHANGES_REQUESTED** [review]
Looks good. However, the build failed because of the clippy issues.

**Comment by kdembler** [comment]
@ignazio-bovo I think we can change the target branch to `rhodes`?

**Review by shamil-gadelshin — APPROVED** [review]
LGTM

**Pull request merged**
