### PR TITLE
Crt contstraints

### PR DESCRIPTION
**Pull request by dobertRowneySr**
fixes:
- max yearly patronage rate 
- patronage rate computation & approximation updated
- patronage tests refactored & updated
- add max limit for transfers
- adds benchmarks for amm (as #4481 has lost all changes)

ref: #4151 

Relevant files:
``` 
Cargo.lock
bin/node/src/chain_spec/project_token_config.rs
chain-metadata.json
cli/src/graphql/generated/schema.ts
distributor-node/src/services/networking/query-node/generated/schema.ts
runtime-modules/common/src/lib.rs
runtime-modules/common/src/numerical.rs
runtime-modules/content/src/benchmarks/benchmarking.rs
runtime-modules/content/src/benchmarks/mod.rs
runtime-modules/content/src/lib.rs
runtime-modules/content/src/tests/creator_tokens/issuer_transfer.rs
runtime-modules/content/src/tests/fixtures.rs
runtime-modules/content/src/tests/mock.rs
runtime-modules/content/src/weights.rs
runtime-modules/project-token/src/benchmarking.rs
runtime-modules/project-token/src/errors.rs
runtime-modules/project-token/src/events.rs
runtime-modules/project-token/src/lib.rs
runtime-modules/project-token/src/tests/amm.rs
runtime-modules/project-token/src/tests/canonical.rs
runtime-modules/project-token/src/tests/fixtures.rs
runtime-modules/project-token/src/tests/mock.rs
runtime-modules/project-token/src/tests/mod.rs
runtime-modules/project-token/src/tests/patronage.rs
runtime-modules/project-token/src/tests/split.rs
runtime-modules/project-token/src/tests/test_utils.rs
runtime-modules/project-token/src/tests/transfer.rs
runtime-modules/project-token/src/types.rs
runtime-modules/project-token/src/weights.rs
runtime-modules/proposals/codex/Cargo.toml
runtime-modules/proposals/codex/src/lib.rs
runtime-modules/proposals/codex/src/tests/mock.rs
runtime-modules/proposals/codex/src/tests/mod.rs
runtime-modules/proposals/codex/src/types.rs
runtime-modules/proposals/codex/src/weights.rs
runtime/src/integration/proposals/proposal_encoder.rs
runtime/src/lib.rs
runtime/src/proposals_configuration/defaults.rs
runtime/src/proposals_configuration/mod.rs
runtime/src/proposals_configuration/playground.rs
runtime/src/proposals_configuration/staging.rs
runtime/src/proposals_configuration/testing.rs
runtime/src/weights/rocksdb_weights.rs
storage-node/src/services/queryNode/generated/schema.ts
tests/network-tests/src/graphql/generated/schema.ts
types/src/augment/augment-api-consts.ts
types/src/augment/augment-api-errors.ts
types/src/augment/augment-api-events.ts
types/src/augment/augment-api-query.ts
types/src/augment/augment-api-tx.ts
types/src/augment/lookup.ts
types/src/augment/registry.ts
types/src/augment/types-lookup.ts
```

### CODE REVIEW

**Comment by dobertRowneySr** [comment]
Implementation requires fixed point arithmetic (`sp_runtime::Perthing` and not floats https://substrate.stackexchange.com/questions/146/can-you-use-floating-point-numbers-or-math-in-the-runtime)

**Comment by bedeho** [comment]
Why do we need this now for CRT constraints specifically and not before?

**Comment by dobertRowneySr** [comment]
> Why do we need this now for CRT constraints specifically and not before?

before we used the computation  (blocks * block_rate) = total_rate for computing the patronage (this was the implementation before this PR without use of any decimal numbers).
We have said that we want the computation to be (1 + yearly_rate)^(blocks_since_last_claim/ blocks_in_a_year) to be a more faithful representation for a real world interest rate computation, we now need decimal numbers and a fixed point representation

**Comment by dobertRowneySr** [comment]
closing in favour of #4750

**Pull request closed without merging**
