### PR TITLE
Rename working groups in Pioneer v1

### PR DESCRIPTION
**Pull request by DzhideX**
This PR addresses the changes proposed here: https://github.com/Joystream/joystream/issues/3119

Updated in:
- Tokenomics page
- Proposals page
- Working Groups page

I haven't updated the descriptions for these new working groups (yet) as I think Ben could probably do a better job. We also probably want to mention which group name here corresponds to which group name in the runtime (like Bedeho says to reduce confusion) as not only are they used in CLI but also in the chain state tab and more..

Edit: I've went ahead and added descriptions on my own. Let me know if it needs changing!

### CODE REVIEW

**Review by Lezek123 — CHANGES_REQUESTED** [review]
Looks good, but a few suggestions:
- `Opportunities` tab (`working-groups/opportunities`) still shows "old" working groups names in filter dropdown as opening labels etc., there is no reference to `Builders` / `Marketing` / `HR`
- On Tokenomics page only new names are shown and there is no reference to `Alpha`, `Beta`, `Gamma`, which I think goes against what's been stated in [the issue](https://github.com/Joystream/joystream/issues/3119):
    > Since these names are indeed used in CLI , it could be sensible to somehow mention these cryptic names still as well, but less prominent.

**Comment by DzhideX** [comment]
Thank you for these suggestions! I went and addressed them but some notes wrt them:
1. I've updated the filter dropdown and opening labels but I couldn't find any other ones (that aren't user input) as the code is a bit convoluted (for example I thought maybe `<OpeningTitle/>`/`JobSpecifics.title` but wasn't quite sure). Let me know if there are any other ones that I may have missed!
2. I wasn't too sure where to put them as the amount of space in the table is already pretty sparse. I've put the extra data into the `helpText` for each of them and hopefully that should be enough?

Edit: Initially I also didn't want to clutter the space in the filter/label but maybe we can add a (for example) `(Operations Group ...)` there or would that be too much?

**Review by Lezek123 — COMMENTED** [review]
I think that's good enough, although I was imagining `Operations Working Group X` more like a small text under the "common" working group name, for example:

Working groups overveiw:
image

Opportunities filtering:
image

Tokenomics:
image

_Those are just quick examples, so they're not very well styled, but you get the idea._

Let me know what do you think.

**Comment by DzhideX** [comment]
I think that's actually a great idea. It looks much better that way!

>Those are just quick examples, so they're not very well styled, but you get the idea.

I don't necessarily think so, maybe just the padding/margins need some work.

I'll do it that way then!

**Comment by DzhideX** [comment]
Okay, I've went ahead and implemented it in:
- Tokenomics
- Proposals
- WGs
- WGs Opportunities filter

Since you didn't say anything against my label comment I didn't add any further info there (I assume you agree that it would clutter it)?

**Review by Lezek123 — APPROVED** [review]
LGTM!

> Since you didn't say anything against my label comment I didn't add any further info there (I assume you agree that it would clutter it)?

Yeah, I think it looks good as is, there is already enough information on the page now for the user to be able to figure out which group is which.

**Comment by freakstatic** [comment]
@DzhideX I believe that Beta is Marketing and Gamma is HR :sweat:

**Comment by freakstatic** [comment]
image

Source: https://blog.joystream.org/sumer-kpis/

**Comment by freakstatic** [comment]
in this PR it seems to be the other way around
image

**Pull request merged**
