### PR TITLE
Joystream CLI - media:uploadVideo - allow json input

### PR DESCRIPTION
**Pull request by Lezek123**
Fixes conflicts in https://github.com/Joystream/joystream/pull/1693

Introduces a way to provide json input for `media:uploadVideo` and skip the confirmation, allowing this command to be used in tests and  for batch uploads, ie.:

```
yarn joystream-cli media:uploadVideo ~/Video1.mp4 -c 84 -i ~/VideoInput1.json --confirm
yarn joystream-cli media:uploadVideo ~/Video2.mp4 -c 84 -i ~/VideoInput2.json --confirm
```
_batch.sh_

```
{
    "title": "Batch Video 1",
    "description": "Batch Video 1",
    "thumbnailUrl": "",
    "isPublic": true,
    "isExplicit": true,
    "hasMarketing": true,
    "language": { "existing": { "code": "EN" } },
    "category": { "existing": { "name": "Music" } },
    "license": { "new": { "knownLicense": { "existing": { "code": "CC_BY" } } } },
    "media": {
      "new": {
        "encoding": { "existing": { "name": "H.264_MP4" } }
      }
    }
}
```
_Example VideoInput1.json_

I also added a way to switch account by specifying a flag to `account:choose`, so that the accounts can be easily changed when running scripts:

```
yarn joystream-cli account:choose -a 5FHneW46xGXgs5mUiveU4sbTyGBzmstUspZC92UhjJM694ty
```

### CODE REVIEW

**Review by bwhm — CHANGES_REQUESTED** [review]
Tested and it works well!
I do have have one issue not specific to this pr, but still:
- The CLI (not the runtime?) requires `publishedBeforeJoystream` to be a positive integer. This makes dates prior to 1970 impossible... Not sure if this something hydra enforces as well, but has to be corrected regardless...

Also:
- Will this be updated when/if #1818 is merged?

**Comment by Lezek123** [comment]
Updated the PR:
- Added `CreativeCommon` license attribution handling (in the end I added it to `License` schema, so it will require query node / Atlas schema changes)
- Bumped upload limit to 2 GB (CLI, storage node)
- Changed `Video` runtime schema to allow negative integer values for `publishedBeforeJoystream` (this required some tweaks in the CLI, as it turned out that `@polkadot/types` `Int32.toJson()` returns hex string instead of number, as it does for `Uint32`)

**Comment by Lezek123** [comment]
Example video input to test recent changes (`publishedBeforeJoystream` set to 1930 + license attribution added):
```
{
    "title": "my video",
    "description": "my video",
    "thumbnailUrl": "",
    "isPublic": true,
    "isExplicit": true,
    "hasMarketing": true,
    "language": { "existing": { "code": "EN" } },
    "category": { "existing": { "name": "Music" } },
    "license": { "new": {
	"knownLicense": {
		"existing": { "code": "CC_BY" }
	},
	"attribution": "Created by Joystream"
    } },
    "media": {
      "new": {
        "encoding": { "existing": { "name": "H.264_MP4" } }
      }
    },
    "publishedBeforeJoystream": -1262307553
}
```

**Comment by mnaamani** [comment]
Looks good, works as advertised.

Tried it also with yes command to figure out if the `--confirm` was really necessary..

`yes | yarn joystream-cli media:uploadVideo ~/Video1.mp4 -c 84 -i ~/VideoInput1.json`

```
? Do you confirm the provided input? Yes
y
y
y
.
. quite a lot more of these :)
.
y
y
y
y

Sending contentDirectory.transaction extrinsic...
Extrinsic successful!
```

If the joystream-cli closes `stdin` after it knows it will no longer take input, then we wouldn't see that many `y`s and could be an alternative.

**Review by mnaamani — APPROVED** [review]

**Comment by mnaamani** [comment]
I have one recommendation, is it possible when passing in the input with `-i` to try to validate the input schema before doing the upload, or provide an argument to do a "dry run" which we have done for some other commands?

**Review by mnaamani — APPROVED** [review]
No changes required (only recommendation)

**Pull request merged**
