### PR TITLE
Bumped hydra dependencies in QN 

### PR DESCRIPTION
**Pull request by zeeshanakram3**
This PR:

- Bumps hydra dependencies in the QN for BigInt fix(https://github.com/Joystream/hydra/pull/516) 
- Bumps `query-node` patch version for new release i.e. `0.1.0 -> 0.1.1`

### CODE REVIEW

**Comment by mnaamani** [comment]
LGTM, I'm syncing a new query node instance against mainnet to confirm there are no isssues.

**Review by mnaamani — APPROVED** [review]

**Comment by mnaamani** [comment]
I deployed this fix to mainnet production QN
cc: @thesan

**Comment by mnaamani** [comment]
@zeeshanakram3 needs minor conflict fix since we bumped the metadata protobuf package version
"@joystream/metadata-protobuf": "^2.5.1",

**Review by Lezek123 — COMMENTED** [review]
Looks good, but since we already started bumping QN versions, I think you should bump `query-node` and `query-node/mappings` version in this PR aswell.

**Comment by mnaamani** [comment]
> Looks good, but since we already started bumping QN versions, I think you should bump `query-node` and `query-node/mappings` version in this PR aswell.

Yes let bump it to 1.0.0 - ref https://github.com/Joystream/joystream/pull/4607 @zeeshanakram3

**Comment by zeeshanakram3** [comment]
> > Looks good, but since we already started bumping QN versions, I think you should bump `query-node` and `query-node/mappings` version in this PR aswell.
> 
> Yes let bump it to 1.0.0 - ref #4607 @zeeshanakram3

Bumped both packages' versions to `1.0.0` in 4ed7414
@mnaamani @Lezek123

**Review by Lezek123 — APPROVED** [review]
LGTM

**Pull request merged**
