### PR TITLE
Revert wrong "commit revert" on "Pioneer - Improve forum performance #2568 PR"

### PR DESCRIPTION
**Pull request by freakstatic**
This reverts commit 1a5cd18623a1fc0dfe25af30ac5099794bf66b3b.

### CODE REVIEW

**Comment by freakstatic** [comment]
So I did a big mistake on [here](https://github.com/Joystream/joystream/pull/2568) and reverted the optimizations from [here](https://github.com/Joystream/joystream/pull/2564) :facepalm:

**Comment by mnaamani** [comment]
Is voting broken? I'm surprised this PR is quite old. Requested review from @Lezek123 

cc: @bwhm

**Comment by freakstatic** [comment]
> Is voting broken? I'm surprised this PR is quite old. Requested review from @Lezek123
> 
> cc: @bwhm

not broken, just slow to load the votes when using a "council key"

**Comment by traumschule** [comment]
replaces use of .size by .entries https://github.com/Joystream/joystream/pull/2564#pullrequestreview-729401559

**Comment by mnaamani** [comment]
pioneer is no longer maintained in this repo

**Pull request closed without merging**
