### PR TITLE
Query node schema fixes

### PR DESCRIPTION
**Pull request by metmirr**

### CODE REVIEW

**Comment by mnaamani** [comment]
Metin could you resolve merge conflict here. So I can test along with updated babylon branch changes to the content-dir-consts.ts

**Comment by mnaamani** [comment]
I fixed conflict locally, then tried to create a channel with the cli using https://github.com/Joystream/joystream/pull/1727

```
MokoBook:joystream mokhtar$ yarn joystream-cli media:createChannel
yarn run v1.22.4
$ /Users/mokhtar/joystream/joystream/node_modules/.bin/joystream-cli media:createChannel
? handle mokhtar
? description mokhtar's channel
? Do you want to provide optional coverPhotoUrl? No
? Do you want to provide optional avatarPhotoURL? No
? isPublic Yes
? Do you want to provide optional language? No
{
    handle: "mokhtar",
    description: "mokhtar's channel",
    coverPhotoUrl: null,
    avatarPhotoURL: null,
    isPublic: true,
    language: null
}
 Do you confirm the provided input? Yes

Sending contentDirectory.transaction extrinsic...
Extrinsic successful!
```

The processor failed with error: "message: Couldn't find 'Language' entities in the classEntityMap, stack: Error: Couldn't find 'Language' entities in the classEntityMap"

```
2020-11-18T12:14:19.335Z index-builder:processor Processing event contentDirectory.TransactionCompleted, 
          id: 0000000000000054-000004
2020-11-18T12:14:19.335Z index-builder:processor JSON: {
  "id": "0000000000000054-000004",
  "name": "contentDirectory.TransactionCompleted",
  "method": "TransactionCompleted",
  "params": [
    {
      "name": "NO_NAME",
      "type": "Actor",
      "value": {
        "Member": 0
      }
    }
  ],
  "index": 4,
  "blockNumber": 54,
  "extrinsic": {
    "method": "transaction",
    "section": "contentDirectory",
    "versionInfo": "132",
    "signer": "5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY",
    "args": [
      {
        "name": "actor",
        "type": "{\"_enum\":{\"Curator\":\"(CuratorGroupId,u64)\",\"Member\":\"MemberId\",\"Lead\":\"Null\"}}",
        "value": {
          "Member": 0
        }
      },
      {
        "name": "operations",
        "type": "Vec<OperationType>",
        "value": [
          {
            "CreateEntity": {
              "class_id": 1
            }
          },
          {
            "AddSchemaSupportToEntity": {
              "entity_id": {
                "InternalEntityJustAdded": 0
              },
              "schema_id": 0,
              "parametrized_property_values": [
                {
                  "value": {
                    "InputPropertyValue": {
                      "Single": {
                        "Text": "mokhtar"
                      }
                    }
                  },
                  "in_class_index": 0
                },
                {
                  "value": {
                    "InputPropertyValue": {
                      "Single": {
                        "Text": "mokhtar's channel"
                      }
                    }
                  },
                  "in_class_index": 1
                },
                {
                  "value": {
                    "InputPropertyValue": {
                      "Single": {
                        "Bool": false
                      }
                    }
                  },
                  "in_class_index": 2
                },
                {
                  "value": {
                    "InputPropertyValue": {
                      "Single": {
                        "Bool": false
                      }
                    }
                  },
                  "in_class_index": 3
                },
                {
                  "value": {
                    "InputPropertyValue": {
                      "Single": {
                        "Bool": true
                      }
                    }
                  },
                  "in_class_index": 4
                },
                {
                  "value": {
                    "InputPropertyValue": {
                      "Single": {
                        "Bool": false
                      }
                    }
                  },
                  "in_class_index": 6
                }
              ]
            }
          }
        ]
      }
    ],
    "signature": "0x90a672b9eb1fb0ba6584bcf81af5c27864641c5284fce9ffd257967499d8bd5959cb785f7566dadccc9b84f020ebedc04e12a56f2b5f35ab97b514c09c6f0a87",
    "hash": "0xf5c1d0ae2e2d4ae535ed742ed2d97656ceb73487428af12e1ce5680941de7713",
    "tip": "0"
  }
}
Rolling back the transaction due to errors: {} name: Error, message: Couldn't find 'Language' entities in the classEntityMap, stack: Error: Couldn't find 'Language' entities in the classEntityMap
    at findEntity (/joystream/query-node/mappings/content-directory/get-or-create.ts:76:49)
    at Object.language (/joystream/query-node/mappings/content-directory/get-or-create.ts:108:26)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at Object.createChannel (/joystream/query-node/mappings/content-directory/entity/create.ts:78:24)
    at batchAddSchemaSupportToEntity (/joystream/query-node/mappings/content-directory/transaction.ts:174:11)
    at contentDirectory_TransactionCompleted (/joystream/query-node/mappings/content-directory/transaction.ts:109:3)
    at /joystream/node_modules/@dzlzv/hydra-indexer-lib/src/processor/MappingsProcessor.ts:152:9
    at Object.doInTransaction (/joystream/node_modules/@dzlzv/hydra-indexer-lib/src/db/helper.ts:52:20)
    at MappingsProcessor.processEventBlock (/joystream/node_modules/@dzlzv/hydra-indexer-lib/src/processor/MappingsProcessor.ts:145:7)
    at MappingsProcessor.processingLoop (/joystream/node_modules/@dzlzv/hydra-indexer-lib/src/processor/MappingsProcessor.ts:124:11)
Stopping the proccessor due to errors: {} name: Error, message: Error: Couldn't find 'Language' entities in the classEntityMap, stack: Error: Error: Couldn't find 'Language' entities in the classEntityMap
    at Object.doInTransaction (/joystream/node_modules/@dzlzv/hydra-indexer-lib/src/db/helper.ts:62:11)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at MappingsProcessor.processEventBlock (/joystream/node_modules/@dzlzv/hydra-indexer-lib/src/processor/MappingsProcessor.ts:145:7)
    at MappingsProcessor.processingLoop (/joystream/node_modules/@dzlzv/hydra-indexer-lib/src/processor/MappingsProcessor.ts:124:11)
    at MappingsProcessor.start (/joystream/node_modules/@dzlzv/hydra-indexer-lib/src/processor/MappingsProcessor.ts:83:5)
    at QueryNodeManager.process (/joystream/node_modules/@dzlzv/hydra-indexer-lib/src/node/QueryNodeManager.ts:78:5)
    at runProcessor (/joystream/query-node/generated/indexer/index.ts:92:3)
    at /joystream/query-node/generated/indexer/index.ts:33:5
    at Command.<anonymous> (/joystream/query-node/generated/indexer/index.ts:22:7)
Error: Error: Error: Couldn't find 'Language' entities in the classEntityMap
    at MappingsProcessor.processingLoop (/joystream/node_modules/@dzlzv/hydra-indexer-lib/src/processor/MappingsProcessor.ts:137:15)
```

**Comment by metmirr** [comment]
It should be fine now, `Channel.language` was non-nullable field.

**Comment by mnaamani** [comment]
I expect the query-node integration test to fail due to the schema changes, renaming.

**Comment by mnaamani** [comment]
Are you planning to do additional updates based on https://github.com/Joystream/joystream/issues/1698 in this PR? Otherwise I can merge

**Comment by metmirr** [comment]
> Are you planning to do additional updates based on #1698 in this PR? Otherwise I can merge

There is one issue left, I will let you know when its ready!

**Pull request merged**
