### PR TITLE
remove unused CouncilRewardClaimed runtime event

### PR DESCRIPTION
**Pull request by zeeshanakram3**
SSIA.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202078489349362/1203779348414479) by [Unito](https://www.unito.io)

### CODE REVIEW

**Review by dobertRowneySr — APPROVED** [review]
LGTM

**Comment by mnaamani** [comment]
@zeeshanakram3 I think it makes sense to target ephesus branch instead of master

**Comment by zeeshanakram3** [comment]
> @zeeshanakram3 I think it makes sense to target ephesus branch instead of master

Done

**Comment by zeeshanakram3** [comment]
> @zeeshanakram3 I think it makes sense to target ephesus branch instead of master

@mnaamani done

**Review by mnaamani — APPROVED** [review]

**Pull request merged**
