### PR TITLE
Fixes Suggested in Substrate v3 Review

### PR DESCRIPTION
**Pull request by mnaamani**
Apply some of the fixes suggested in https://github.com/Joystream/joystream/issues/4170

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202132419573087/1202792013068412) by [Unito](https://www.unito.io)

### CODE REVIEW

**Review by dobertRowneySr — COMMENTED** [review]
Looks good to me.
I specifically looked for the followings:
- [X] Updating to v0.9.24-
- [X] adding =#[sp_version::runtime_version]= attribute to RuntimeVersion
- [X] revise Our configured bonding duration
- [X] change "substrate-node" in node/build.rs to "joystream-node"
- [X] Removed any conditional code on try-runtime feature in cargo.toml
- [X] joystream/node builds
- [X] cargo tests passing

and they were all addressed

**Review by Lezek123 — COMMENTED** [review]
- :heavy_check_mark:  `inspect` commands added and working correctly (although inspecting blocks by number/hash works only when using a chainspec file)
- :heavy_check_mark: `#[sp_version::runtime_version]` macro works as expected (adds a custom `runtime_version` section in the wasm blob)
- :heavy_check_mark: Joystream's substrate fork upgraded to `v0.9.24-1`
- :heavy_check_mark: `BondingDuration`/`SlashDeferDuration` now the same as in substrate node
- :heavy_check_mark: `cargo test --release --package joystream-node -- --ignored` passes
- :heavy_check_mark: `substrate-node` changed to `joystream-node` in `bin/node/build.rs`
- :heavy_check_mark:  `try-runtime` removed
- :negative_squared_cross_mark: For some reason the CI checks are failing: https://github.com/Joystream/joystream/runs/8190538703?check_suite_focus=true, https://github.com/Joystream/joystream/runs/8190528788?check_suite_focus=true

**Comment by mnaamani** [comment]
@Lezek123 Looks like the build error is specific to the docker build. Some cargo dependency `prost-build v0.10.4` has a custom build step that is using `cmake` which seems to be missing in the docker image. Will have to add it.

```
error: failed to run custom build command for `prost-build v0.10.4`

Caused by:
  process didn't exit successfully: `/joystream/target/release/build/prost-build-916fcd6d7d706d8f/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-changed=/usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/prost-build-0.10.4/third-party/protobuf/cmake
  CMAKE_TOOLCHAIN_FILE_x86_64-unknown-linux-gnu = None
  CMAKE_TOOLCHAIN_FILE_x86_64_unknown_linux_gnu = None
  HOST_CMAKE_TOOLCHAIN_FILE = None
  CMAKE_TOOLCHAIN_FILE = None
  CMAKE_GENERATOR_x86_64-unknown-linux-gnu = None
  CMAKE_GENERATOR_x86_64_unknown_linux_gnu = None
  HOST_CMAKE_GENERATOR = None
  CMAKE_GENERATOR = None
  CMAKE_PREFIX_PATH_x86_64-unknown-linux-gnu = None
  CMAKE_PREFIX_PATH_x86_64_unknown_linux_gnu = None
  HOST_CMAKE_PREFIX_PATH = None
  CMAKE_PREFIX_PATH = None
  CMAKE_x86_64-unknown-linux-gnu = None
  CMAKE_x86_64_unknown_linux_gnu = None
  HOST_CMAKE = None
  CMAKE = None
  running: "cmake" "/usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/prost-build-0.10.4/third-party/protobuf/cmake" "-Dprotobuf_BUILD_TESTS=OFF" "-DCMAKE_INSTALL_PREFIX=/joystream/target/release/build/prost-build-5458256b7b8f21af/out" "-DCMAKE_C_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_C_COMPILER=/usr/bin/cc" "-DCMAKE_CXX_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_CXX_COMPILER=/usr/bin/c++" "-DCMAKE_ASM_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_ASM_COMPILER=/usr/bin/cc" "-DCMAKE_BUILD_TYPE=Debug"

  --- stderr
  thread 'main' panicked at '
  failed to execute command: No such file or directory (os error 2)
  is `cmake` not installed?
```

Also after updating from carthage I noticed types are out of sync with runtime so I prepared a fix https://github.com/Joystream/joystream/pull/4259

**Review by Lezek123 — APPROVED** [review]
LGTM

**Comment by mnaamani** [comment]
Not sure why this was closed? Asana integration

**Review by dobertRowneySr — APPROVED** [review]
LGTM

**Pull request merged**
