### PR TITLE
Hydra/configure two separate databases

### PR DESCRIPTION
**Pull request by mnaamani**
Attempt to build and configure hydra to use two separate datbases, one for the indexer and the other for the graphql-server which is populated by the processor.

Update the build script for query-node to also use common `.env` file at the root to avoid confusion.

### CODE REVIEW

**Comment by metmirr** [comment]
## Running without docker

Currently, the indexer and mappings processor uses the same ts file and the same env variable for the database name. After code generation `TYPEORM_DATABASE` env variable in `generated/indexer/.env` is set to `query_node_indexer`. So when I run the processor it uses the same database(indexer database) which makes it fail because of the missing tables.

Maybe for time being, we can update the package json script for the processor (`query-node/package.json`) as follows:

`DEBUG=${DEBUG} TYPEORM_DATABASE=${DB} ts-node index.ts process`

And run the processor:

`DEBUG=* DB=query_node_processor yarn workspace query-node-root processor:start`

_Note: in the new hydra_v1 indexer and processor are separated_

**Review by metmirr — APPROVED** [review]
Looks good, had no issues running with docker.

**Comment by mnaamani** [comment]
> ## Running without docker
> 
> Currently, the indexer and mappings processor uses the same ts file and the same env variable for the database name. After code generation `TYPEORM_DATABASE` env variable in `generated/indexer/.env` is set to `query_node_indexer`. So when I run the processor it uses the same database(indexer database) which makes it fail because of the missing tables.
> 
> Maybe for time being, we can update the package json script for the processor (`query-node/package.json`) as follows:
> 
> `DEBUG=${DEBUG} TYPEORM_DATABASE=${DB} ts-node index.ts process`
> 
> And run the processor:
> 
> `DEBUG=* DB=query_node_processor yarn workspace query-node-root processor:start`
> 
> _Note: in the new hydra_v1 indexer and processor are separated_

Great thanks for spotting that. I applied a slightly different approach to make it simpler so you don't have to remember to set `DB=` when running `yarn workspace query-node-root processor:start` by adding a `processor-start.sh` to read the database name from the `.env` file.

**Comment by mnaamani** [comment]
Hmm in last commit I changed port from 4100 to 4000 for the indexer-api-gateway in .env now I'm seeing error in processor in ci-checks.. will try to fix

```
Server listening to 3000, metrics exposed on /metrics endpoint
  "migrations": [
FetchError: request to http://localhost:4000/graphql failed, reason: connect ECONNREFUSED 127.0.0.1:4000
    at ClientRequest.<anonymous> (/joystream/node_modules/cross-fetch/node_modules/node-fetch/lib/index.js:1461:11)
    null
    at ClientRequest.emit (events.js:314:20)
    at ClientRequest.EventEmitter.emit (domain.js:483:12)
    at Socket.socketErrorListener (_http_client.js:427:9)
    at Socket.emit (events.js:314:20)
    at Socket.EventEmitter.emit (domain.js:483:12)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
```

**Comment by mnaamani** [comment]
last issue isn't to do with port number changes, I think its just sometimes taking long time for some of the docker services to start.

**Comment by mnaamani** [comment]
Not sure why I didn't spot this earlier, the error is actually in the tests:

```
/home/runner/work/joystream/joystream/tests/network-tests/src/flows/contentDirectory/creatingChannel.ts:23
  assert.equal(queriedChannel.handle, channel.handle, 'Should be equal')
                              ^
TypeError: Cannot read property 'handle' of undefined
    at assertChannelMatchQueriedResult (/home/runner/work/joystream/joystream/tests/network-tests/src/flows/contentDirectory/creatingChannel.ts:23:31)
    at Object.channelCreation [as default] (/home/runner/work/joystream/joystream/tests/network-tests/src/flows/contentDirectory/creatingChannel.ts:41:3)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at scenario (/home/runner/work/joystream/joystream/tests/network-tests/src/scenarios/content-directory.ts:42:3)
error Command failed with exit code 1.
```

**Comment by mnaamani** [comment]
Finally figured out that I was reloading the .env vars that were being "exported" in the shell (despite using `set +a`) so it was overriding the values set in docker-compose

**Pull request merged**
