### PR TITLE
Remove council blog pallet and proposals

### LINKED ISSUE #3662: Remove council blog pallet and proposals
This should be metaprotocol based, and its not needed for mainnet scope either way, so remove pallet and also related proposals

* `Create Blog Post`
* `Edit Blog Post`
* `Lock Blog Post`
* `Unlock Blog Post`

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202132419573087/1202172189692174) by [Unito](https://www.unito.io)

### PR DESCRIPTION
**Pull request by L3pereira**
* Closes #3662

Remove blog related proposals e9b64555db02a2513f5ea58514cc3ff031f0a652
Remove pallet-blog e43711eecb453cf177dcb9cf8979b8da307bb5fa
Remove blog related typescript f046818b0db3a991d54a62d87c8a8900e33c55dc

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202132419573087/1202476361030601) by [Unito](https://www.unito.io)

### CODE REVIEW

**Review by dobertRowneySr — COMMENTED** [review]
LGTM, just one question: are we still keeping the `types/src/blog.ts`?

**Comment by L3pereira** [comment]
> LGTM, just one question: are we still keeping the `types/src/blog.ts`?

No, I didn't see that file, it should also be deleted

**Review by dobertRowneySr — CHANGES_REQUESTED** [review]
Delete `types/src/blog.ts`

**Review by dobertRowneySr — APPROVED** [review]

**Review by dobertRowneySr — CHANGES_REQUESTED** [review]
_EDIT_:  
There is just a small problem with the types now: https://github.com/Joystream/joystream/runs/6937965925?check_suite_focus=true#step:4:197
you should have the CI checks for types and runtime build passing

**Review by dobertRowneySr — APPROVED** [review]
LGTM, types error are now only related to Project token types library not existing.
The PR should be merged and the Project token types should be resolved in another PR if necessary

**Comment by bedeho** [comment]
I am not sure we should have merged this here, we should merge it in Carthage after it has absorbed the new work frmo mokhtar.

**Pull request merged**
