### PR TITLE
Olympia query node nft issue buy now

### PR DESCRIPTION
**Pull request by ondratra**
QN mappings covering NFT transactional status change on video update + setting buy-now state on video creation and updates.

PR is built on top of https://github.com/Joystream/joystream/pull/3281 and expects it to be merged first.

### CODE REVIEW

**Comment by ondratra** [comment]
At the current state, issuing NFT with the initial state `BuyNow` throws an error `Error: 1010: Invalid Transaction: Transaction has a bad signature` on sending a transaction. The cause of this error is still unknown. Usually, an error like this occurs when invalid types are used, but they seem to be ok. 

Issuing NFT with initial transaction status `Idle` or `Auction` works fine. The problem is with `BuyNow` only. 

Relevant parts of code:
- runtime type https://github.com/Joystream/joystream/pull/3282/files#diff-c1b161f32cc691d160772b747698284d395c54f35b44d8f5f6b333f006d1340fR539
- type definition https://github.com/Joystream/joystream/pull/3282/files#diff-f55e462681a1baec4fe2aacbae51a591ea3abc5a3f048c68db08d3953f73ea4eR86 
- extrinsic call that will fail https://github.com/Joystream/joystream/pull/3282/files#diff-64a6b3108d189ec8ae3b896171805c387b702ca3bf7faec1663dd57ff84b26ebR1062

The quickest way to test the error is:
```
yarn build:node:docker
yarn build:packages
JOYSTREAM_NODE_TAG="db1f3ddd2f4a888a40c0b8521a61cc401f950d27" ./query-node/run-tests.sh content-directory
```
There have been some parts of `content-directory` tests temporarly commented out to reduce the time to test this particular feature/error.

**Comment by ignazio-bovo** [comment]
I remember discussing a similar issue with Leszek, some times ago. The solution was:
To rebuild joystream node image

**Comment by ondratra** [comment]
I've tried to get rid of all docker images I have on my system
```
docker-compose down -v
docker system prune -a
```
and then rebuild the node and run tests again
```
yarn build:node:docker
yarn build:packages
JOYSTREAM_NODE_TAG="db1f3ddd2f4a888a40c0b8521a61cc401f950d27" ./query-node/run-tests.sh content-directory
```
but the error still occurs. The error also occurs in our GitHub CI as can be seen here https://github.com/Joystream/joystream/runs/5309319722?check_suite_focus=true#step:8:4665

**Comment by ondratra** [comment]
The error mentioned above was caused by bad order of properties `InitTransactionalStatus` in types.
In runtime there is 
```
pub enum InitTransactionalStatusRecord<
    BlockNumber: BaseArithmetic + Copy + Default,
    MemberId: Default + Copy + Ord,
    Balance: Default + Clone + BaseArithmetic,
> {
    Idle,
    BuyNow(Balance),
    InitiatedOfferToMember(MemberId, Option<Balance>),
    Auction(AuctionParams<BlockNumber, Balance, MemberId>),
}
```
but in types there originally was: 
```
export class InitTransactionalStatus extends JoyEnum({
  Idle: Null,
  InitiatedOfferToMember: Tuple.with([MemberId, Option.with(Balance)]),
  BuyNow: Balance,
  Auction: AuctionParams,
}) {}
```

The order of `InitiatedOfferToMember` and `BuyNow` was bad while `Idle` and `Auction` were in their right places. That's why issuing NFT with initial transactional status `Idle` and `Auction` were working, but `BuyNow` was failing.

**Comment by mnaamani** [comment]
Should this be targetting rhodes ?

**Review by zeeshanakram3 — APPROVED** [review]
LGTM

**Pull request merged**
