### PR TITLE
Remove old versioned store related modules

### PR DESCRIPTION
**Pull request by iorveth**
This PR aims to:
1. Remove old versioned-store, versioned-store-permissions, content-working-group modules from the node rntime.
1. Refactor chainspec `content_config.rs`

Closes https://github.com/Joystream/joystream/issues/1735

### CODE REVIEW

**Review by shamil-gadelshin — CHANGES_REQUESTED** [review]
Compilation errors on testing. Please fix to enable the review.

**Comment by iorveth** [comment]
Compilation errors fixed.

> Compilation errors on testing. Please fix to enable the review.

**Review by shamil-gadelshin — CHANGES_REQUESTED** [review]
Please, remove the migration code from this PR.

Bedeho's quote: "The old version store and permissions module and content dir working group should just be stripped out, no migration of current state. They are not used anywhere anyway."

**Comment by iorveth** [comment]
> Please, remove the migration code from this PR.
> 
> Bedeho's quote: "The old version store and permissions module and content dir working group should just be stripped out, no migration of current state. They are not used anywhere anyway."

Done

**Review by shamil-gadelshin — APPROVED** [review]
LGTM

**Pull request merged**
