### PR TITLE
refs #897 add discussion post form loader for better ux

### LINKED ISSUE #897: Show progress feedback when submitting discussion posts
When submitting a post on a proposal discussion, it takes a very long time, and there is no direct feedback that anything is going on in the UI, beyond general alert labels. It's not clear whether it failed or not. Some sort of spinner indicating the in-flight submission would make it a better experience.

### PR DESCRIPTION
**Pull request by Dimitreee**
**Add simple loader to discussion post form controls while submitting the post message.**

Resolves #897 

Снимок экрана 2020-09-24 в 11 52 29

### CODE REVIEW

**Comment by Dimitreee** [comment]
For some reason MacOS Checks ci pipeline was canceled. Any suggestions?

**Comment by mnaamani** [comment]
> For some reason MacOS Checks ci pipeline was canceled. Any suggestions?

I can't tell why it was cancelled but i can run it again manually.

**Comment by mnaamani** [comment]
We occasionally see issues running ci checks on Mac, I see a few others failing in other PRs right now so its probably an issue which should get resolved by github tech team soonish.

**Comment by Dimitreee** [comment]
It's green now, thanks

**Comment by mnaamani** [comment]
Thank you for your contribution. Sorry we didn't get to review this before releasing the latest version.
Could you update the PR again from master branch.

**Comment by Dimitreee** [comment]
Ready for review

**Comment by mnaamani** [comment]
Tested works nicely. Adding screenshot to zoom in on spinner in case it wasn't clear in the opening comment:

Screen Shot 2020-09-25 at 12 18 03 PM

Just need a confirmation from @Lezek123 and happy to merge.

**Review by Lezek123 — APPROVED** [review]
Nice and simple improvement!

**Comment by Dimitreee** [comment]
Please, provide more issues. :)

**Comment by mnaamani** [comment]
> Please, provide more issues. :)

Certainly. @bwhm might be able to point you at some issues in his backlog

**Pull request merged**
