### PR TITLE
Increase max working group mint capacity

### PR DESCRIPTION
**Pull request by mnaamani**
Council can now set working group mint capacity to 50 Million (up from 5 Million) via proposal.

### CODE REVIEW

**Comment by Lezek123** [comment]
Looks like a small change in Pioneer proposal form validation may be needed: https://github.com/Joystream/joystream/blob/master/pioneer/packages/joy-proposals/src/validationSchema.ts#L80

**Comment by mnaamani** [comment]
> Looks like a small change in Pioneer proposal form validation may be needed: https://github.com/Joystream/joystream/blob/master/pioneer/packages/joy-proposals/src/validationSchema.ts#L80

Thanks will prepare a PR

**Comment by mnaamani** [comment]
@bwhm We can merge this, pioneer will auto-build so the limit increase will be allowed in the UI but fail in runtime. As long as community is aware I see no need to "pause" auto-deploy of pioneer. ACK ?

**Review by shamil-gadelshin — CHANGES_REQUESTED** [review]
Looks good. However, it seems you forgot to update the node version. We are merging to master, so it is relevant.

**Comment by mnaamani** [comment]
> Looks good. However, it seems you forgot to update the node version. We are merging to master, so it is relevant.

The node version is not as important to bump as the spec version if we haven't published a new binary, and since I bumped the node version in https://github.com/Joystream/joystream/pull/2513 I didn't bother doing it again here, but I think its good practice to always bump it. Will push an update.

**Comment by mnaamani** [comment]
Integration tests are failing I think I need to update the test related to mint capacity..

**Pull request closed without merging**
