### PR TITLE
fix: remove duplicate files

### PR DESCRIPTION
**Pull request by metmirr**
This PR removes extra files introduced in this commit https://github.com/Joystream/joystream/commit/ee298fccf8e38d062216c44c30ab7d8401d17675

### CODE REVIEW

**Comment by Lezek123** [comment]
Some observations:
- Removing those lowercase files breaks some links in `SUMMARY.md` (https://github.com/metmirr/joystream/blob/query_node/SUMMARY.md), not sure if it matters (I think out those broken links only `runtime/changelog.md` was potentially useful)
- The commit mentioned in the PR description (https://github.com/Joystream/joystream/commit/ee298fccf8e38d062216c44c30ab7d8401d17675) also introduced `README.md` file inside `pioneer/packages` which is the reason (or one of the reasons) why Pioneer build fails on the current `query_node` branch (https://github.com/Joystream/joystream/pull/1379/checks?check_run_id=1122795062)

**Review by Lezek123 — COMMENTED** [review]
I'm not sure how to address this, but as far as I understand the issue is that:
- Inside `pioneer` directory there are a few `.md` files that have uppercase/mixed-case names (ie. `BOUNTIES.md`, `ToS.md`, `Privacy.md` etc.)
- Some tool on `query_node` branch (`gitbook`?) generated a tree with links to all `.md` files in the monorepo (`/SUMMARY.md`),  did some formatting on existing `.md` files and also created a bunch of new `.md` files (either copies of some existing files or empty ones with just a title), involving some lowercase copies of a few files that were uppercase/mixed-case. It was all done in this commit: https://github.com/Joystream/joystream/commit/ee298fccf8e38d062216c44c30ab7d8401d17675
- This resulted in a few instances of `.md` files with same name but different case beeing committed, so currently on this branch there exists ie. both `pioneer/BOUNTIES.md` and `pioneer/bounties.md`. While this is a non-issue on Linux, which uses case-sensitive filesystem, it creates some problems on Mac which are hard for me to debug (I'm using Ubuntu).

I'm not sure how much we need `SUMMARY.md` and all those other files that `gitbook` apparently generated and whether there is a plan to use this tool again in the future. Perhaps some input from @dmitrii will be useful here (since the issue was introduced in this PR: https://github.com/Joystream/joystream/pull/446)

### My proposition:

**1. Remove those files completely (regardless of the case):**
- `pioneer/CHANGELOG.md` - it's a `polkadot-js/apps` relic anyway
- `pioneer/CONTRIBUTING.md` - same as above
- `pioneer/BOUNTIES.md` - same as above
- all `.md` files and `md` folders that were created in `pioneer/packages` in https://github.com/Joystream/joystream/commit/ee298fccf8e38d062216c44c30ab7d8401d17675 - there are a lot of empty files or files that are just copies of other files. Some of them were created in locations that cause Pioneer build script to break (ie. anything directly in `pioneer/packages`, see CI checks below)
- `cli/bin/README.md`
- `cli/bin/run.md`
- `docs/README.md` and `docs/using-docker/README.md`? (they just contain a header)

**2. Delete only lowercase:**
- `pioneer/packages/joy-pages/src/md/privacy.md`
- `pioneer/packages/joy-pages/src/md/tos.md`
- `runtime/changelog.md`

**3. Fix links in `/SUMMARY.md` if needed**

**Comment by dzhelezov** [comment]
It's unfortunate the Gitbook commit has screwed the unrelated docs, sorry about that. I can't really comment on the content of the pioneer docs, so whatever changes were made can be rolled backed. The gitbook is now disconnected from this repo, and I think @Lezek123 plan is sound.

**Comment by metmirr** [comment]
Based on @Lezek123 suggestion all the `md` files introduced in this commit ee298fc have been deleted including `SUMMARY.md`

**Pull request merged**
