### PR TITLE
carthage faucet v2

### PR DESCRIPTION
**Pull request by mnaamani**
Using new faucet implementation https://github.com/Joystream/membership-faucet/pull/17

### CODE REVIEW

**Review by Lezek123 — CHANGES_REQUESTED** [review]
When trying to use `BALANCE_CREDIT=20000000000`:
```
faucet                   | [2022-08-04 08:33:01]: server started at http://localhost:3002
faucet                   | [2022-08-04 08:34:38]: register request for test1 from 192.168.0.32
faucet                   | [2022-08-04 08:34:38]: Error: Assertion failed
faucet                   |     at assert (/faucet/node_modules/@polkadot/util/node_modules/bn.js/lib/bn.js:6:21)
faucet                   |     at BN.iaddn (/faucet/node_modules/@polkadot/util/node_modules/bn.js/lib/bn.js:2229:5)
faucet                   |     at BN.addn (/faucet/node_modules/@polkadot/util/node_modules/bn.js/lib/bn.js:2297:25)
faucet                   |     at JoyApi.invitingAccountHasFundsToGift (/faucet/lib/joyApi.js:171:57)
faucet                   |     at processTicksAndRejections (internal/process/task_queues.js:95:5)
faucet                   |     at async register (/faucet/lib/register.js:90:29)
faucet                   |     at async Mutex.<anonymous> (/faucet/lib/app.js:60:13)
```

I inspected the `bn.js` library and I noticed this:
```javascript
  BN.prototype.iaddn = function iaddn (num) {
    assert(typeof num === 'number');
    assert(num < 0x4000000);
```

It seems like `addn` is limited to numers smaller than `0x4000000` (`67_108_864`)

**Comment by mnaamani** [comment]
Interesting observation, I wonder why they are limiting.. In any case I updated the faucet to use `add` instead https://github.com/Joystream/membership-faucet/pull/17/commits/dd5e066cd2d96ddd5580c2a8912b553369bb9a13

**Comment by mnaamani** [comment]
hmm for some reason some test is failing, after I updated from carthage..

```
2022-08-05T11:52:20.163Z integration-tests:job:content directory (with CLI) flow 2 failed:
AssertionError: expected '146' to equal '145'
    at /home/runner/work/joystream/joystream/tests/network-tests/src/fixtures/content/commentAndReaction/CreateCommentsFixture.ts:71:14
    at Array.map (<anonymous>)
    at CreateCommentsFixture.assertQueriedCommentsAreValid (/home/runner/work/joystream/joystream/tests/network-tests/src/fixtures/content/commentAndReaction/CreateCommentsFixture.ts:66:13)
    at CreateCommentsFixture.runQueryNodeChecks (/home/runner/work/joystream/joystream/tests/network-tests/src/fixtures/content/commentAndReaction/CreateCommentsFixture.ts:92:10)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async FixtureRunner.runQueryNodeChecks (/home/runner/work/joystream/joystream/tests/network-tests/src/Fixture.ts:198:5)
    at async FixtureRunner.runWithQueryNodeChecks (/home/runner/work/joystream/joystream/tests/network-tests/src/Fixture.ts:203:5)
    at async commentsAndReactions (/home/runner/work/joystream/joystream/tests/network-tests/src/flows/content/commentsAndReactions.ts:111:3)
    at async /home/runner/work/joystream/joystream/tests/network-tests/src/Job.ts:103:11 {
  showDiff: true,
  actual: '146',
  expected: '145',
  operator: 'strictEqual'
}
2022-08-05T11:52:20.198Z integration-tests:job:content directory (with CLI) [Failed]
```

**Comment by mnaamani** [comment]
Re-ran the integration check and it passed. Might be worth looking into it?

**Review by Lezek123 — APPROVED** [review]
LGTM

**Pull request merged**
