### PR TITLE
Alexandria Release

### PR DESCRIPTION
**Pull request by mnaamani**

### CODE REVIEW

**Comment by bwhm** [comment]
Should we merge now, or wait for launch?
@mnaamani Remember to change configs for deploying pioneer on netlify!

**Comment by mnaamani** [comment]
> Should we merge now, or wait for launch?
> @mnaamani Remember to change configs for deploying pioneer on netlify!

We can merge now. Config is ready.

Do we want https://github.com/Joystream/joystream/pull/1421 merged also ?

**Comment by bwhm** [comment]
> > Should we merge now, or wait for launch?
> > @mnaamani Remember to change configs for deploying pioneer on netlify!
> 
> We can merge now. Config is ready.
> 
> Do we want #1421 merged also ?

Done :)

**Comment by bwhm** [comment]
👍

**Pull request merged**
