### PR TITLE
Upgrade hydra-processor

### PR DESCRIPTION
**Pull request by metmirr**
This PR upgrades hydra-processor to the latest version and updates mappings. Also removes all dependencies for the old indexer and processor.

Steps to test locally:
1. docker-compose up -d db
2. yarn workspace query-node-root build
3. yarn workspace query-node-root db:migrate
4. docker-compose up -d processor

### CODE REVIEW

**Comment by mnaamani** [comment]
I'm getting error building, and I see the same error in the CI check:

```
Mokhtars-MacBook-Pro:query-node mokhtar$ yarn build
yarn run v1.22.4
$ ./build.sh
$ rm -rf ./generated
$ hydra-cli codegen
  ✔ Set up a new Warthog project
  ✔ Prepare project files
  ✔ Install dependencies
  ✔ Generate server sources
  ✔ Warthog codegen
  ↓ Create DB [skipped]
    → Skipping. Create the database and run the migrations with yarn db:prepare and yarn db:migrate
  ↓ Create DB schema [skipped]
    → Skipping. Create the database and run the migrations with yarn db:prepare and yarn db:migrate
  ↓ Run DB migrations [skipped]
    → Skipping. Create the database and run the migrations with yarn db:prepare and yarn db:migrate

Generating the GraphQL server... done
Building mappings...
$ rm -rf lib && tsc --build tsconfig.json
cp: ./mappings/lib/mappings/generated/types/typedefs.json: No such file or directory
error Command failed with exit code 1.
```

**Comment by metmirr** [comment]
> I'm getting error building, and I see the same error in the CI check:
> 
> ```
> Mokhtars-MacBook-Pro:query-node mokhtar$ yarn build
> yarn run v1.22.4
> $ ./build.sh
> $ rm -rf ./generated
> $ hydra-cli codegen
>   ✔ Set up a new Warthog project
>   ✔ Prepare project files
>   ✔ Install dependencies
>   ✔ Generate server sources
>   ✔ Warthog codegen
>   ↓ Create DB [skipped]
>     → Skipping. Create the database and run the migrations with yarn db:prepare and yarn db:migrate
>   ↓ Create DB schema [skipped]
>     → Skipping. Create the database and run the migrations with yarn db:prepare and yarn db:migrate
>   ↓ Run DB migrations [skipped]
>     → Skipping. Create the database and run the migrations with yarn db:prepare and yarn db:migrate
> 
> Generating the GraphQL server... done
> Building mappings...
> $ rm -rf lib && tsc --build tsconfig.json
> cp: ./mappings/lib/mappings/generated/types/typedefs.json: No such file or directory
> error Command failed with exit code 1.
> ```

is building mapping ok?

**Comment by metmirr** [comment]
@mnaamani  Since we don't have a live chain `hydra-typegen` would fail. As a temporary solution, I commit types that generated by hydra-typegen, once we have a live chain we can rollback it.

**Comment by mnaamani** [comment]
Seems to be building now, but when it runs the processor is failing with:

```
INFO: Starting the processor
2021-03-31T21:19:46.171Z hydra-processor:dal Total events count 0
ERROR: {
  "errno": -2,
  "syscall": "open",
  "code": "ENOENT",
  "path": "/joystream/query-node/mappings/lib/mappings/generated-t/types/typedefs.json"
} name: Error, message: ENOENT: no such file or directory, open '/joystream/query-node/mappings/lib/mappings/generated-t/types/typedefs.json', stack: Error: ENOENT: no such file or directory, open '/joystream/query-node/mappings/lib/mappings/generated-t/types/typedefs.json'
    at Object.openSync (fs.js:462:3)
    at Object.readFileSync (fs.js:364:35)
    at Object.<anonymous> (/joystream/query-node/mappings/lib/mappings/generated-t/types/index.js:10:47)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at /joystream/node_modules/@dzlzv/hydra-processor/lib/process/HandlerLookupService.js:71:88
INFO: Shutting down...
INFO: Closing the database connection...
2021-03-31T21:19:46.203Z hydra-processor:runner Done closing the connection
2021-03-31T21:19:46.203Z hydra-processor:runner Exiting
error Command failed with exit code 1.
error Command failed with exit code 1.
```

Is there a typo in the path?

`/joystream/query-node/mappings/lib/mappings/generated-t/types/typedefs.json`

"generated-t"

**Comment by metmirr** [comment]
> Seems to be building now, but when it runs the processor is failing with:
> 
> ```
> INFO: Starting the processor
> 2021-03-31T21:19:46.171Z hydra-processor:dal Total events count 0
> ERROR: {
>   "errno": -2,
>   "syscall": "open",
>   "code": "ENOENT",
>   "path": "/joystream/query-node/mappings/lib/mappings/generated-t/types/typedefs.json"
> } name: Error, message: ENOENT: no such file or directory, open '/joystream/query-node/mappings/lib/mappings/generated-t/types/typedefs.json', stack: Error: ENOENT: no such file or directory, open '/joystream/query-node/mappings/lib/mappings/generated-t/types/typedefs.json'
>     at Object.openSync (fs.js:462:3)
>     at Object.readFileSync (fs.js:364:35)
>     at Object.<anonymous> (/joystream/query-node/mappings/lib/mappings/generated-t/types/index.js:10:47)
>     at Module._compile (internal/modules/cjs/loader.js:999:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
>     at Module.load (internal/modules/cjs/loader.js:863:32)
>     at Function.Module._load (internal/modules/cjs/loader.js:708:14)
>     at Module.require (internal/modules/cjs/loader.js:887:19)
>     at require (internal/modules/cjs/helpers.js:74:18)
>     at /joystream/node_modules/@dzlzv/hydra-processor/lib/process/HandlerLookupService.js:71:88
> INFO: Shutting down...
> INFO: Closing the database connection...
> 2021-03-31T21:19:46.203Z hydra-processor:runner Done closing the connection
> 2021-03-31T21:19:46.203Z hydra-processor:runner Exiting
> error Command failed with exit code 1.
> error Command failed with exit code 1.
> ```
> 
> Is there a typo in the path?
> 
> `/joystream/query-node/mappings/lib/mappings/generated-t/types/typedefs.json`
> 
> "generated-t"

This is intentional actually, b/c we are ignoring all the `generated` folders. And this is a temporary solution so whenever there is a live rpc then we can drop `generated-t` folder which will be generated by hydra-typegen then.

**Review by mnaamani — APPROVED** [review]

**Pull request merged**
